### PR TITLE
Update Walletconnect

### PR DESCRIPTION
**Pull request by hexyls**
closes https://github.com/protofire/omen-exchange/issues/1243

note: To test you need to reinstall packages

To test mobile deep linking, on your mobile phone open https://omen-mobile.vercel.app and login with wallet connect, you should see this list of mobile wallets you can choose from:

Screen Shot 2021-04-14 at 3 09 28 pm

### CODE REVIEW

**Review by KadenZipfel — APPROVED** [review]
Much needed feature! Code looks good and works well for me, tested on iPhone. Can we get someone to confirm it works on Android?

**Comment by pimato** [comment]
@hexyls I have connected my metamask mobile on IOS through the Rinkeby testnetwork and it looks like Omen still shows the network picker with Mainnet connection:
Bildschirmfoto 2021-04-15 um 09 20 32

**Review by pimato — CHANGES_REQUESTED** [review]
see comment

**Review by Mi-Lan — DISMISSED** [review]
@hexyls Managed to connect with Android to metamask wallet. I had issue with signed transactions both for the relayer. 
Screenshot 2021-04-15 at 12 27 43
Also on mobile it just loads indefinitely or fails transaction....
Screenshot_20210415-114855_Chrome
Screenshot_20210415-115314_Chrome
- And i had trouble with being unable to switch to xDai it says mainnet while its on xDai for mobile
Screenshot_20210415-120345_Chrome

**Comment by Mi-Lan** [comment]
also this x in the top right of modal seems a little f-ed up...
Screenshot 2021-04-15 at 12 41 45

**Comment by Mi-Lan** [comment]
One more thing when i connect to xDai via wallet connect metamsk i get this error....
Screenshot 2021-04-15 at 12 25 01

**Comment by hexyls** [comment]
Thanks for the helpful feedback guys, I think I fixed the issue where the network is incorrect.

Also it turns out signatures through wallet connect are handled [completely differently](https://github.com/WalletConnect/walletconnect-monorepo/issues/347) to a standard web3 provider, so after a bit of trial and error I think I got sigs + the relay working properly too (though I need to test it across a couple of different wallets).

In general one issue I found is that connectivity can be flaky, e.g. occasionally you can make a tx and open up the mobile wallet and the tx does not show up for signing. Unfortunately that is not really something I can fix, it comes down to the wallet connect protocol and how each of the wallets are set up.

**Comment by pimato** [comment]
> In general one issue I found is that connectivity can be flaky, e.g. occasionally you can make a tx and open up the mobile wallet and the tx does not show up for signing. Unfortunately that is not really something I can fix, it comes down to the wallet connect protocol and how each of the wallets are set up.

Jup, I can reproduce it! I am using `Metamask Mobile` on `IOS` and at some point the app is not able to show me the sign message.  Once I close the app, reopen the message shows up. Does not look like it is something on our side so def. good to go!

**Review by pimato — APPROVED** [review]

**Comment by Mi-Lan** [comment]
> Thanks for the helpful feedback guys, I think I fixed the issue where the network is incorrect.
> 
> Also it turns out signatures through wallet connect are handled [completely differently](https://github.com/WalletConnect/walletconnect-monorepo/issues/347) to a standard web3 provider, so after a bit of trial and error I think I got sigs + the relay working properly too (though I need to test it across a couple of different wallets).
> 
> In general one issue I found is that connectivity can be flaky, e.g. occasionally you can make a tx and open up the mobile wallet and the tx does not show up for signing. Unfortunately that is not really something I can fix, it comes down to the wallet connect protocol and how each of the wallets are set up.

Yeah i was thinking the same thing sometimes it prompts sign messages and most time it doesn't....Thats not on our side 👍

**Comment by Mi-Lan** [comment]
Screenshot 2021-04-16 at 11 56 54
@hexyls It seems that I still get this error when wanting to connect to xDai metmask...Also is https://omen-mobile.vercel.app/ updated?

**Comment by Mi-Lan** [comment]
Rest of the feature on desktop work great! Managed to buy,sell,deposit,withdraw on both categorical and scalar markets without a hiccup now!

**Comment by pimato** [comment]
> Screenshot 2021-04-16 at 11 56 54
> @hexyls It seems that I still get this error when wanting to connect to xDai metmask...Also is https://omen-mobile.vercel.app/ updated?

Great catch @Mi-Lan ! I was able to reproduce it by adding xdai to metamask mobile: 
Bildschirmfoto 2021-04-16 um 15 26 38

**Comment by hexyls** [comment]
Nice one @Mi-Lan 🙌 thought that was covered with the last fix (obvs not 😄), thanks for confirming the issue @pimato

Should be fixed now and https://omen-mobile.vercel.app is updated again too 👍

**Review by pimato — APPROVED** [review]
works on Rinkeby, Mainnet & xDai!

**Review by Mi-Lan — APPROVED** [review]
Works great man! Tested it on mobile and desktop and it didn't have any issues 💣

**Pull request merged**
