### PR TITLE
fix proxy factory address

### PR DESCRIPTION
**Pull request by hexyls**
Bit of a mutability bug here where the cpk network addresses were being modified directly:

```
networks[network.chainId].proxyFactoryAddress = relayProxyFactoryAddress
```

This could cause the xdai cpk address to be incorrect.

Fixed by creating a new object and modifying that instead:

```
[network.chainId]: { ...cpkAddresses }
```

### CODE REVIEW

**Review by Mi-Lan — APPROVED** [review]

**Comment by hexyls** [comment]
Snuck in an additional change - the incorrect xdai balance was being displayed in the header when connected directly to xdai.

**Review by pimato — APPROVED** [review]
can we show only two decimals instead of three:
Bildschirmfoto 2021-05-05 um 16 44 44

**Review by pimato — CHANGES_REQUESTED** [review]
see comment

**Comment by hexyls** [comment]
Also updated `formattedEthBalance` -> `formattedNativeBalance`

**Review by pimato — APPROVED** [review]

**Review by KadenZipfel — APPROVED** [review]

**Review by Mi-Lan — APPROVED** [review]
Formatting looks good!

**Pull request merged**
