### PR TITLE
Remove compound logic from market funding

### PR DESCRIPTION
**Pull request by hexyls**
related https://github.com/protofire/omen-exchange/issues/2012 

PR removes compound logic from categorical and scalar market funding (add + remove).

Additional change - Wrapped assets are always unwrapped when removing funding

https://github.com/protofire/omen-exchange/pull/2036 should be merged first

Testing:
- [ ] DAI categorical market add funding
- [ ] DAI categorical market remove funding
- [ ] DAI scalar market add funding
- [ ] DAI scalar market remove funding
- [ ] ETH categorical market add funding
- [ ] ETH categorical market remove funding
- [ ] ETH scalar market add funding
- [ ] ETH scalar market remove funding

### CODE REVIEW

**Review by Mi-Lan — APPROVED** [review]
Testing:
- [x] DAI categorical market add funding
- [ ] DAI categorical market remove funding
- [ ] DAI scalar market add funding
- [ ] DAI scalar market remove funding
- [ ] ETH categorical market add funding
- [ ] ETH categorical market remove funding
- [ ] ETH scalar market add funding
- [ ] ETH scalar market remove funding
Also code looks solid! GJ lets shreeeed it!

**Comment by KadenZipfel** [comment]
Testing:
- [ ] DAI categorical market add funding
- [ ] DAI categorical market remove funding
- [ ] DAI scalar market add funding
- [ ] DAI scalar market remove funding
- [ ] ETH categorical market add funding
- [ ] ETH categorical market remove funding
- [ ] ETH scalar market add funding
- [ ] ETH scalar market remove funding

**Review by KadenZipfel — APPROVED** [review]
Looks good! So nice to see all these red lines 🧘‍♂️

**Comment by pimato** [comment]
- [ ] DAI categorical market add funding
- [ ] DAI categorical market remove funding
- [ ] DAI scalar market add funding
- [ ] DAI scalar market remove funding
- [ ] ETH categorical market add funding
- [ ] ETH categorical market remove funding
- [ ] ETH scalar market add funding
- [ ] ETH scalar market remove funding

**Pull request merged**
