### PR TITLE
Add Open Market Count to Categories

### PR DESCRIPTION
**Pull request by nickplace**
Looks like theres no solid way to get a count for "All categories" but I was able to add counts for open markets when a user chooses specific categories.

### CODE REVIEW

**Comment by pimato** [comment]
Hey @nickplace 
just checked, if I pick Coronavirus I get 12 markets but the market widget listview is not showing anything:
Screenshot 2020-07-03 at 16 51 19

**Comment by pimato** [comment]
Also "News & Politics" is showing 10 markets but there are actually 11:
Screenshot 2020-07-03 at 16 52 30

**Comment by pimato** [comment]
Something is wrong here:
Screenshot 2020-07-03 at 16 55 01

**Comment by nickplace** [comment]
Merged with #920, so closing

**Pull request closed without merging**
