### PR TITLE
Fix/1373 request omen token list data from subgraph

### LINKED ISSUE #1373: Request omen's token-list data from subgraph instead of Infura
Now that we merged the adding of the token-list into the omen subgraph (https://github.com/protofire/omen-subgraph/pull/91) we are able to request token data from the subgraph instead of infura itself.

This is part of a bigger issue which goal is to eliminate infura request as much as possible: https://github.com/protofire/omen-exchange/issues/1346

### PR DESCRIPTION
**Pull request by altbee**
Please test on Rinkeby and use the following thegraph endpoints.

REACT_APP_GRAPH_RINKEBY_HTTP='https://api.thegraph.com/subgraphs/name/astro514/omen-rinkeby'
REACT_APP_GRAPH_RINKEBY_WS='wss://api.thegraph.com/subgraphs/name/astro514/omen-rinkeby'

### CODE REVIEW

**Comment by pimato** [comment]
Hey I am getting:
Bildschirmfoto 2020-11-23 um 21 13 12

```REACT_APP_VERSION=omen
REACT_APP_INFURA_PROJECT_ID="9c6788bb15234036991db4637638429f"
REACT_APP_MARKET_FEE=2.00
REACT_APP_GRAPH_MAINNET_HTTP='https://api.thegraph.com/subgraphs/name/protofire/omen'
REACT_APP_GRAPH_MAINNET_WS='wss://api.thegraph.com/subgraphs/name/protofire/omen'
REACT_APP_GRAPH_RINKEBY_HTTP='https://api.thegraph.com/subgraphs/name/astro514/omen-rinkeby'
REACT_APP_GRAPH_RINKEBY_WS='wss://api.thegraph.com/subgraphs/name/astro514/omen-rinkeby'
REACT_APP_KEY_INFURA_API_KEY=6ad6d4a4ec79442eacfa967652729d1c
REACT_APP_ETH_NETWORKS=mainnet
REACT_APP_GIT_SHA=21e344c954e0022c95c0b1b30ccc38663a797734
NODE_ENV=production```

when I trying to click on a currency in the currency dropdown.

**Review by pimato — CHANGES_REQUESTED** [review]
looks like there is a bug

**Comment by liaojikunwork** [comment]
@pimato, did you connect the metamask before you test it?
You're getting that error because it fetches the data from mainnet before wallet is connected.

On the home page, please connect Wallet first and then try on Rinkeby.

**Review by Mi-Lan — APPROVED** [review]
LGTM!

**Review by pimato — APPROVED** [review]

**Review by kadenzipfel — APPROVED** [review]

**Comment by joeleonjr** [comment]
Hi! I'm a security researcher @TruffleSecurity. I found a valid API key leaked in a comment in this Issue. I highly recommend rotating the API key immediately (not just deleting the comment). Here's a blog post I wrote on remediating these types of vulnerabilities: https://trufflesecurity.com/blog/remediate-leaked-api-keys-with-key-rotation.<br><br>If you can't find the leaked API key, you can use the following [TruffleHog](https://github.com/trufflesecurity/trufflehog) command to automatically scan for it:<br>`trufflehog github --repo https://github.com/<your_username>/<your_reponame> --issue-comments --only-verified`<br><br>If it's not clear where/what the security issue is, please let me know. I'd be happy to help. Please note that the API key might be in the past edit of a comment.<br><br><br><br>(cc @pimato)

**Pull request merged**
