### PR TITLE
Add relay check to useRealityLink

### PR DESCRIPTION
**Pull request by KadenZipfel**
Partially closes: https://github.com/protofire/omen-exchange/issues/1745

The problem with this solution is although we now have the correct reality link, we still have to switch our network to xDai to view the reality item.

### CODE REVIEW

**Review by hexyls — APPROVED** [review]
👍

Yeah it is annoying that users have to switch over to the xdai network once they are outside Omen. It looks like they even have to refresh the page after switching networks (not a lot we can do about that).

**Review by pimato — APPROVED** [review]
tested, works!

**Review by Mi-Lan — APPROVED** [review]
Better then before! But still sucks to have to switch network...Would be cool if they added feature to check markets out chain agnostic @pimato could they make this happen?

**Comment by pimato** [comment]
> Better then before! But still sucks to have to switch network...Would be cool if they added feature to check markets out chain agnostic @pimato could they make this happen?

I think reality.eth needs to include the connect network feature by metamask at some point. So people can connect easier to xDai.

**Pull request merged**
