### PR TITLE
Add airdrop card to guild modal

### PR DESCRIPTION
**Pull request by hexyls**
related https://github.com/protofire/omen-exchange/issues/1861

Testing:
- [ ] Using the guild modal - Can check and claim airdrop for an eligible address on rinkeby

### CODE REVIEW

**Review by pimato — CHANGES_REQUESTED** [review]
the claim component is still visible in the lock Omen token modal:
https://user-images.githubusercontent.com/5337809/126330453-6ac3ea9d-ab58-4529-a274-2db9c14f54c6.mov

**Comment by pimato** [comment]
lets increase the padding top & bottom here from 16px to 20px:
Bildschirmfoto 2021-07-20 um 15 19 17

**Comment by pimato** [comment]
lets add the default modal padding to the divider here:
Bildschirmfoto 2021-07-20 um 15 22 43

**Comment by pimato** [comment]
@hexyls what is the easiest way to test the claim and check functionality with a new address? I think I used all my addresses which have claimable OMN tokens so I can´t really test it now.

**Comment by hexyls** [comment]
@pimato added a new rinkeby airdrop just for testing purposes, got these testing addresses from Alchemy:

@pimato: 0x81a94868572ea6e430f9a72ed6c4afb8b5003fdf
@KadenZipfel: 0x3111327edd38890c3fe564afd96b4c73e8101747
@Mi-Lan: 0x11aa7ef6d9fb561b2050c90f655286ea2409a477
@Frankaus: 0x4502166be703312eae5137ad7399393b09471f27

The 'Check Address' claim can be done with any unused address in `services/airdrop/0xf20676162Af8B5f26D8c61288089a2bf63042Ab2/json`

**Comment by pimato** [comment]
Hey @hexyls just tried to claim and one thing that bothers me is that after the claim transaction like here:

https://user-images.githubusercontent.com/5337809/126487368-661118e1-a854-40e4-8835-5cb311e5b23b.mov

the Omen Membership modal Airdrop component is not getting updated:
Bildschirmfoto 2021-07-21 um 14 19 01

**Review by pimato — CHANGES_REQUESTED** [review]
see comments

**Comment by pimato** [comment]
I´ve created two related issues which should be fixed in separate PRs:
https://github.com/protofire/omen-exchange/issues/2114
https://github.com/protofire/omen-exchange/issues/2115

**Comment by hexyls** [comment]
@pimato just a recap of what I mentioned in keybase - the OMN balance in the guild modal doesn't update because the airdrop is not using the official rinkeby OMN token. Just for testing this PR I have changed the OMN address to the test token so you can see it working, will change back once you can see the whole flow working as expected 👍

Also updated to clear claim balances after successful claims

**Comment by pimato** [comment]
testing:

- [ ] can claim airdrop
- [ ] after claim - balance updates in guild modal
- [ ] after claim - claimable balance updates / resets

**Review by pimato — CHANGES_REQUESTED** [review]
it seems like the Omen Guild Membership Modal is keeping old state. For example I previously was in the Lock Omen Token View and closed the modal. Once I clicked on the OMN token balance button again the Lock Omen Token View is still visibile:

https://user-images.githubusercontent.com/5337809/126613227-18053e5b-c485-41e7-a37b-e57a30eeec8a.mov

It should reset all the time the modal has been closed.

**Review by pimato — APPROVED** [review]

**Review by KadenZipfel — COMMENTED** [review]
The code looks good to me, but I couldn't manage to test it because none of my addresses have a claim. I saw you setup a new claim but I don't see the file in the repo, could it have been left out some how?

**Comment by hexyls** [comment]
@KadenZipfel yeah some testing addresses were left out, updated rinkeby airdrop - your testing address is 0x3111327edd38890c3fe564afd96b4c73e8101747

**Comment by Mi-Lan** [comment]
@hexyls Good job man! Works as expected!

https://user-images.githubusercontent.com/33226956/126972051-66cb3d86-cd99-4580-8aad-006bb0cef286.mov

**Review by Mi-Lan — APPROVED** [review]

**Review by KadenZipfel — APPROVED** [review]
Looks good! Tx for reference: https://blockscout.com/poa/xdai/tx/0x5c28247c43de8d50d33a7e2c5d588aaee0015a96122ace448dcebbfa40ba0cba

**Pull request merged**
