### PR TITLE
Fix undefined list item current prediction

### PR DESCRIPTION
**Pull request by KadenZipfel**
Closes: https://github.com/protofire/omen-exchange/issues/1724

Maybe there's something better to put than 'Unknown'?

### CODE REVIEW

**Review by hexyls — APPROVED** [review]
hmmm couldn't think of anything better than Unknown, so looks good to me

**Comment by pimato** [comment]
@KadenZipfel there is no way to check what the prediction was right before the liquidity was removed?

**Review by pRoy24 — APPROVED** [review]
LGTM

**Comment by KadenZipfel** [comment]
> @KadenZipfel there is no way to check what the prediction was right before the liquidity was removed?

I think it could be done with a subgraph update but I think it might be confusing for users since re-adding liquidity would just set the probability to 50%. What do you think?

**Review by pimato — APPROVED** [review]

**Pull request merged**
