### PR TITLE
Withdraw not working fix

### PR DESCRIPTION
**Pull request by Mi-Lan**

### CODE REVIEW

**Comment by Mi-Lan** [comment]
@KadenZipfel Not sure whats the reason but im getting vercel error

 {"error":"Relay: Transaction will fail: processing response error (body=\"{\\\"jsonrpc\\\":\\\"2.0\\\",\\\"error\\\":{\\\"code\\\":-32015,\\\"message\\\":\\\"VM execution error.\\\",\\\"data\\\":\\\"revert: CPKFactory: execTransaction Failed\\\"},\\\"id\\\":44}\", error={\"code\":-32015,\"data\":\"revert: CPKFactory: execTransaction Failed\"}, requestBody=\"{\\\"method\\\":\\\"eth_call\\\",\\\"params\\\":[{\\\"gas\\\":\\\"0x2dc6c0\\\",\\\"gasPrice\\\":\\\"0x3b9aca00\\\",\\\"from\\\":\\\"0x1b50bc65403333f921fe627eda28c119a93aa15f\\\",\\\"to\\\":\\\"0x7b9756f8a7f4208fe42fe8de8a8cc5aa9a03f356\\\",\\\"data\\\":\\\"0x68bb7c6900000000000000000000000032654c77b9cb34dc6e90301c2fc7b0f5c1efe5d5000000000000000000000000035000fc773f4a0e39fcded08a46abbdbf196fd30000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000016000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002c000000000000000000000000000000000000000000000000000000000000001248d80ff0a000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000ce007301cfa0e1756b71869e93d4e4dca5c7d0eb0aa6000000000000000000000000000000000000000000000001307c1f0711c4aaa100000000000000000000000000000000000000000000000000000000000000245d1e9307000000000000000000000000162eb61a498c34676625ca3aceb3f92508f49aac001b50bc65403333f921fe627eda28c119a93aa15f000000000000000000000000000000000000000000000000000aa87bee5380000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000041e26ef0c3ad24e17ed91a2244033f082aa44b651ca574d1ef67f0b5d26c5f934d145ff6ec8b418ee66f54617289ab3133d871550a55f47585a06aae90bc2862f42000000000000000000000000000000000000000000000000000000000000000\\\"},\\\"latest\\\"],\\\"id\\\":44,\\\"jsonrpc\\\":\\\"2.0\\\"}\", requestMethod=\"POST\", url=\"https://rpc.xdaichain.com/\", code=SERVER_ERROR, version=web/5.0.13)"}

**Comment by Mi-Lan** [comment]
I also tried simulating it on tenderly but couldn't get much out of it https://dashboard.tenderly.co/dxdao/dxdao-proposal-simulation/simulator/ee5616a7-8f20-4d94-a56f-59dba9a53692

**Comment by hexyls** [comment]
@Mi-Lan at some point we started charging relay fees for withdrawals again 🤔 so when you hit max withdraw on dai the tx fails - added a commit to remove fees again

**Comment by Mi-Lan** [comment]
> @Mi-Lan at some point we started charging relay fees for withdrawals again 🤔 so when you hit max withdraw on dai the tx fails - added a commit to remove fees again

Ohhh yeah! I totally forgot about that, nice catch! It works now as it should!

**Comment by Mi-Lan** [comment]
@hexyls @KadenZipfel This looks good to me!

**Review by Frankaus — APPROVED** [review]
Working out fine here:) I deposited DAI and withdrew. Tried to deposit wEth but didn't have sufficient funds for the 20$ tx. I changed many times wallet account and RPC endpoints and it works fine. I created and funded a scalar market and it worked fine.

**Comment by KadenZipfel** [comment]
> @hexyls @KadenZipfel I removed exclude fee from the omni bridge transaction since relay was giving out this error for the withdraw...
> Screenshot 2021-07-15 at 15 28 02

Yeah, should be good to include the fee since you're withdrawing a different token

**Review by KadenZipfel — APPROVED** [review]
Looks good!

**Review by pimato — APPROVED** [review]
just tested it and it works fine!"

**Pull request merged**
