### PR TITLE
Remove remaining compound logic

### PR DESCRIPTION
**Pull request by hexyls**
closes https://github.com/protofire/omen-exchange/issues/2012 

Removes the remaining compound stuff peppered throughout the app 

Testing:
- [ ] DAI categorical market top details correct
- [ ] DAI scalar market top details correct
- [ ] ETH categorical market top details correct
- [ ] ETH scalar market top details correct
- [ ] Can claim bond successfully

### CODE REVIEW

**Review by pimato — CHANGES_REQUESTED** [review]
Connection-type: xdai tight integration

It looks like the app is freezing on this market: 
http://localhost:3000/#/0x528a5648be1287b08d57603205e557a7569386e2

I made a video:
https://user-images.githubusercontent.com/5337809/123970844-c90a3a80-d9b9-11eb-8202-4d7b34b165b4.mov

**Comment by KadenZipfel** [comment]
Testing:
- [ ] DAI categorical market top details correct
- [ ] DAI scalar market top details correct
- [ ] ETH categorical market top details correct
- [ ] ETH scalar market top details correct
- [ ] Can claim bond successfully

**Review by KadenZipfel — COMMENTED** [review]
Everything looks good, but have we considered backwards compatibility? What happens if someone tries to withdraw liquidity on an existing compound market?

**Comment by hexyls** [comment]
@KadenZipfel hadn't thought about that, just tested it though and looks like it works ok - e.g. withdrawing from a cDai market gives cDai directly instead of converting back to Dai.

We should consider if we want to remove the cTokens from the token list too 🤔

**Comment by KadenZipfel** [comment]
Testing backwards compatibility:
- [ ] Create compound market on `master` branch
- [ ] Buy shares
- [ ] Switch to this branch
- [ ] Sell some shares
- [ ] Bond on final outcome
- [ ] Successfully redeem cDai for correct answer

**Review by KadenZipfel — APPROVED** [review]

**Comment by Mi-Lan** [comment]
Testing backwards compatibility:
- [x] Create compound market on `master` branch
- [x] Buy shares
- [x] Switch to this branch
- [x] Sell some shares
- [x] Bond on final outcome
- [x] Successfully redeem cDai for correct answer

**Review by Mi-Lan — APPROVED** [review]

**Review by pimato — APPROVED** [review]
Works!

**Pull request merged**
