### PR TITLE
Fetch liquidity values in data hooks

### PR DESCRIPTION
**Pull request by hexyls**
closes https://github.com/protofire/omen-exchange/issues/2140

Testing:

Market list:
- [ ] Liquidity values load instantly
- [ ] Liquidity values are correct

Market details:
- [ ] Liquidity values load instantly
- [ ] Liquidity values are correct

### CODE REVIEW

**Comment by pimato** [comment]
Market list:
- [ ] Liquidity values load instantly
- [ ] Liquidity values are correct

Market details:
- [ ] Liquidity values load instantly
- [ ] Liquidity values are correct

**Review by pimato — CHANGES_REQUESTED** [review]
It looks like we are not using our rounding to `K` anymore!
now:
Bildschirmfoto 2021-08-04 um 13 15 51

should:
Bildschirmfoto 2021-08-04 um 13 15 47

**Comment by Mi-Lan** [comment]
@hexyls I hope you don't mind me fixing comment geronimo just outlined...So we get the release going asap!

**Review by Mi-Lan — APPROVED** [review]
LGTM!
Market list:
- [x] Liquidity values load instantly
- [x] Liquidity values are correct

Market details:
- [x] Liquidity values load instantly
- [ ] Liquidity values are correct

**Review by pimato — APPROVED** [review]

**Pull request merged**
