### PR TITLE
Two fpmm factories & final fpmm v2

### PR DESCRIPTION
**Pull request by KadenZipfel**
Closes: https://github.com/protofire/omen-exchange/issues/1940

**Note: Do not merge! For testing/review purposes only**

This is our testing grounds for our new fpmm contract (hopefully final version before audit). Along with testing that both factories coexist without issues. Note that earnings data is currently unavailable due to a subgraph bug.

**Testing (Rinkeby only):**
- [x] Successful market creation
  - [x] Categorical
  - [x] Scalar
- [x] All markets work as expected
  - [x] Old markets
  - [x] New markets
      - [x] Buy
      - [x] Sell
      - [x] Deposit
      - [x] Withdraw
      - [x] Bond
      - [x] Redeem

We will first do a full testing run through with protocol fee off, then we'll do it again with the protocol fee turned on

**Testing w/ protocol fee on (Rinkeby only):**

We should now do another run through of testing to make sure the protocol fee works as expected. The protocol fee has been set to take 10% of the LP fee. This should be working properly, and tested, on both newly created v2 markets and those created before the protocol fee was set, e.g. http://localhost:3000/#/0x46524c8a7fcd7696d01687fd30c12a9efaaefb69, http://localhost:3000/#/0x28b09acee7758c2924f5d8177bc4d3f1c7a9bdcd.

For below tests, please share transactions for each so that I can verify that everything looks as expected.

- [ ] V2 markets created before protocol fee was set
  - [x] Deposit https://rinkeby.etherscan.io/tx/0x1a1b6274f594b7f5256a9564f6ee2449a3520c3d0716a4ecb78c1d06ccf4473a
  - [ ] Withdraw
  - [ ] Buy 
  - [ ] Sell
  - [ ] Bond 
  - [ ] Redeem
- [ ] V2 markets created after protocol fee was set
  - [ ] Deposit
  - [ ] Withdraw
  - [ ] Buy 
  - [ ] Sell
  - [ ] Bond 
  - [ ] Redeem

### CODE REVIEW

**Comment by Mi-Lan** [comment]
- [ ] Successful market creation
  - [ ] Categorical
  - [ ] Scalar
- [ ] All markets work as expected
  - [ ] Old markets
  - [ ] New markets
      - [ ] Buy
      - [ ] Sell
      - [ ] Deposit
      - [ ] Withdraw
      - [ ] Bond
      - [ ] Redeem

**Review by Mi-Lan — CHANGES_REQUESTED** [review]
@KadenZipfel I seem to have trouble selling shares on new markets...

https://user-images.githubusercontent.com/33226956/124480522-a310db80-dda7-11eb-9fe5-ca0c5864cf65.mov

Screenshot 2021-07-05 at 15 42 54

**Comment by KadenZipfel** [comment]
> @KadenZipfel I seem to have trouble selling shares on new markets...

Thanks @Mi-Lan for finding that! Looks like there was a calculation error in the sell function on the fpmm which has now been mitigated. New markets should work as expected now

**Comment by pimato** [comment]
**Testing (Rinkeby only):**
- [ ] Successful market creation
  - [ ] Categorical
  - [ ] Scalar
- [ ] All markets work as expected
  - [ ] Old markets
  - [ ] New markets
      - [ ] Buy
      - [ ] Sell
      - [ ] Deposit
      - [ ] Withdraw
      - [ ] Bond
      - [ ] Redeem

**Review by pimato — APPROVED** [review]
I did not encounter any issues. Worked great!

**Comment by pimato** [comment]
@KadenZipfel could you verify the factory contract?
`0x9dd6eB146D7fb98614487617DE608560321E15BE`

**Review by pimato — APPROVED** [review]

**Comment by Frankaus** [comment]
**Testing (Rinkeby only):**

- [ ]  Old markets
  - [ ]  Buy
  - [ ]  Sell
  - [ ]  Deposit
  - [ ]  Withdraw
  - [ ]  Bond

- [ ] New markets
**Categorical:**
- [ ]  Successful market creation
- [ ]  Buy
- [ ]  Sell
- [ ]  Deposit
- [ ]  Withdraw
- [ ]  Bond
- [ ]  Redeem
**Scalar:**
- [ ]  Successful market creation
- [ ]  Buy
- [ ]  Sell
- [ ]  Deposit
- [ ]  Withdraw
- [ ]  Bond
- [ ]  Redeem

**Comment by Mi-Lan** [comment]
**Testing (Rinkeby only):**
  - [x] Old markets
      - [x] Buy
      - [x] Sell
      - [x] Deposit
      - [x] Withdraw
      - [x] Bond
      - [ ] Redeem (http://localhost:3000/#/0x8ef91edbbae569cef2d83aa0b3b0d2a96b136475/finalize)
  - [x] New markets
   - **Categorical**:
      - [x] Successful market creation
      - [x] Buy
      - [x] Sell
      - [x] Deposit
      - [x] Withdraw
      - [x] Bond
      - [x] Redeem
   - **Scalar**:
      - [x] Successful market creation
      - [x] Buy
      - [x] Sell
      - [x] Deposit
      - [x] Withdraw
      - [x] Bond
      - [x] Redeem

**Review by Mi-Lan — APPROVED** [review]
LGTM! All test cases passed!

**Comment by KadenZipfel** [comment]
> https://curate.kleros.io/tcr/0x3b29096b7ab49428923d902cEC3dFEaa49993234/0x20361cd14f92c10f8840aa7d1312db1bed0bbdf0d0902e90526fe3a737f8a5c9?action=challenge
> Not sure I've done it right tho but it tells me '400: Error fetching item'

For future reference, we wanna use Reality for this step - Kleros is only used at the end if users can't agree on Reality. To actually bond and redeem though you should be able to do it directly on Omen once the market has resolved

**Comment by KadenZipfel** [comment]
Testing with protocol fee:

- [ ] V2 markets created before protocol fee was set
  - [x] Deposit https://rinkeby.etherscan.io/tx/0x1a1b6274f594b7f5256a9564f6ee2449a3520c3d0716a4ecb78c1d06ccf4473a
  - [x] Withdraw https://rinkeby.etherscan.io/tx/0x03ec3777535606f7a42f6878697d6eb7813ff619cf9c23ffa95a8eb50f8c6348
  - [x] Buy https://rinkeby.etherscan.io/tx/0xf7123fd1b967a86fa7763ae2d2e887f1f51c759fe735e003b40f6f3053067560
  - [x] Sell https://rinkeby.etherscan.io/tx/0x33c06dec3146d3ca57e260e43d07d3315660de7f7925538b729a98baaa6baee8
  - [ ] Bond 
  - [ ] Redeem
- [ ] V2 markets created after protocol fee was set
  - [x] Create market https://rinkeby.etherscan.io/tx/0x0110c62f8e1e089f356ee094e657fe64af96cf6ee810c9dccc72abd1276049e6
  - [x] Deposit https://rinkeby.etherscan.io/tx/0xbad48ef2aec7fa3df029f23be26fc2319d508023502050260e9d7c6806f093ee
  - [x] Withdraw https://rinkeby.etherscan.io/tx/0xe2e4d8894e19a8d1e3d4c07622b7cd3f338afe05b75229232a03409865ade20a
    - Tx successful but caused a divide by zero that I'll look into
  - [x] Buy https://rinkeby.etherscan.io/tx/0x46571c98e46864e3c691758e89e047dd023b29087859f55c686bc4a6a8394b80
  - [x] Sell https://rinkeby.etherscan.io/tx/0xaf60106fe53fe676543163ff4e3fb7b3b6b3610d714df335a0682039e69ae352
  - [x] Bond https://rinkeby.etherscan.io/tx/0xe60d6efa2cdde17f65683c0a41d9e282e063c4229291c646e20302281dc8aca9
  - [x] Redeem https://rinkeby.etherscan.io/tx/0xa1bacbfbefdc6aa3da63ec29a0fd45a79af02de3f8212a3c7d0a3b8f0a32206b

**Comment by Frankaus** [comment]
> > https://curate.kleros.io/tcr/0x3b29096b7ab49428923d902cEC3dFEaa49993234/0x20361cd14f92c10f8840aa7d1312db1bed0bbdf0d0902e90526fe3a737f8a5c9?action=challenge
> > Not sure I've done it right tho but it tells me '400: Error fetching item'
> 
> For future reference, we wanna use Reality for this step - Kleros is only used at the end if users can't agree on Reality. To actually bond and redeem though you should be able to do it directly on Omen once the market has resolved

Alright noted. Let me try it out again today.

**Review by Frankaus — APPROVED** [review]
I managed to finish the testings and it works fine here. I could not test the bonding of old markets (cause I didn't have one that ended now). I have created another issue because of the user address shown in the history panel which is wrong for the deposit action. 

https://github.com/protofire/omen-exchange/issues/2096

**Comment by Frankaus** [comment]
2nd Round of Testing:

**Testing (Rinkeby only):**

- [x]  Old markets
  - [x]  Buy

  - [x]  Sell

  - [x]  Deposit

  - [x]  Withdraw

  - [ ]  Bond


- [x] New markets

**Categorical:**

- [x]  Successful market creation

- [x]  Buy

- [x]  Sell

- [x]  Deposit

- [x]  Withdraw

- [x]  Bond

- [ ] Redeem

**Scalar:**

- [x]  Successful market creation

- [x]  Buy

- [x]  Sell

- [x]  Deposit

- [x]  Withdraw

- [x]  Bond

- [x]  Redeem

**Comment by hexyls** [comment]
- [x] Successful market creation
  - [x] Categorical
  - [x] Scalar
- [x] All markets work as expected
  - [x] Old markets
- [x] V2 markets created before protocol fee was set
  - [x] Deposit: https://rinkeby.etherscan.io/tx/0xb498a04e743e2c3d831bbfba76ef37ba93a0fa0d7d52e1ea95b8ad205b754a4d
  - [x] Withdraw: https://rinkeby.etherscan.io/tx/0x83f351d1cbe07ca58e472dcd40a27a5353570735c7d671271acfa1932052b734
  - [x] Buy: https://rinkeby.etherscan.io/tx/0x612a945d3bbd767bc807c030b51539a3fc58340191c6ea0af850b2afae05074a
  - [x] Sell: https://rinkeby.etherscan.io/tx/0xfe1473e91be9bbe8c6c5e2d0a6d9a7789996bc1542beab8ac410dcc7e47ce087
- [x] V2 markets created after protocol fee was set
  - [x] Deposit 1 Dai with Account A: https://rinkeby.etherscan.io/tx/0x07a55ebd2a643b83bc2e6ec3e967156bc12768a8a716bd8f25161070aa057b4d
  - [x] Buy 1 Dai with Account B: https://rinkeby.etherscan.io/tx/0xb191b1cb31fc97dfde11a1e061b87675fa09f6c627330c925811d142cdeedb04
  - [x] Withdraw with Account A: https://rinkeby.etherscan.io/tx/0x534e2232181a6c17a47598860a76ce1c589def39d6c58452326efa5db0122a93 
  - [x] Sell (different market): https://rinkeby.etherscan.io/tx/0xcd12b4ab0dab3da506aebe74fd060b21ce04f77ed95924dbf6498635b5ce4696
  - [x] Bond: https://rinkeby.etherscan.io/tx/0xafe92ff116d7498c6b15224a0f9c94d6ee14c6cae12e18b9bf4864790a557b95
  - [x] Redeem: https://rinkeby.etherscan.io/tx/0xb0351210983852ae26ad2eea16cf16ede166a13ef2c17cea8e26337ff92dfc93

So awesome to see the protocol fee in action!

**Comment by Mi-Lan** [comment]
Testing with protocol fee:

- [ ] V2 markets created before protocol fee was set
  - [x] Deposit https://rinkeby.etherscan.io/tx/0x1a1b6274f594b7f5256a9564f6ee2449a3520c3d0716a4ecb78c1d06ccf4473a
  - [x] Withdraw https://rinkeby.etherscan.io/tx/0x03ec3777535606f7a42f6878697d6eb7813ff619cf9c23ffa95a8eb50f8c6348
  - [x] Buy https://rinkeby.etherscan.io/tx/0xf7123fd1b967a86fa7763ae2d2e887f1f51c759fe735e003b40f6f3053067560
  - [x] Sell https://rinkeby.etherscan.io/tx/0x33c06dec3146d3ca57e260e43d07d3315660de7f7925538b729a98baaa6baee8
  - [ ] Bond 
  - [ ] Redeem
- [x] V2 markets created after protocol fee was set
  - [x] Create market https://rinkeby.etherscan.io/tx/0x0110c62f8e1e089f356ee094e657fe64af96cf6ee810c9dccc72abd1276049e6
  - [x] Deposit https://rinkeby.etherscan.io/tx/0xbad48ef2aec7fa3df029f23be26fc2319d508023502050260e9d7c6806f093ee
  - [x] Withdraw https://rinkeby.etherscan.io/tx/0xe2e4d8894e19a8d1e3d4c07622b7cd3f338afe05b75229232a03409865ade20a
  - [x] Buy https://rinkeby.etherscan.io/tx/0x46571c98e46864e3c691758e89e047dd023b29087859f55c686bc4a6a8394b80
  - [x] Sell https://rinkeby.etherscan.io/tx/0xaf60106fe53fe676543163ff4e3fb7b3b6b3610d714df335a0682039e69ae352
  - [x] Bond https://rinkeby.etherscan.io/tx/0xe60d6efa2cdde17f65683c0a41d9e282e063c4229291c646e20302281dc8aca9
  - [x] Redeem https://rinkeby.etherscan.io/tx/0xa1bacbfbefdc6aa3da63ec29a0fd45a79af02de3f8212a3c7d0a3b8f0a32206b

**Comment by Mi-Lan** [comment]
Testing with protocol fee:

- [ ] V2 markets created before protocol fee was set
  - [ ] Deposit 
  - [ ] Withdraw 
  - [ ] Buy 
  - [ ] Sell 
  - [ ] Bond 
  - [ ] Redeem
- [ ] V2 markets created after protocol fee was set
  - [ ] Create market 
  - [ ] Deposit 
  - [ ] Withdraw 
  - [ ] Buy 
  - [ ] Sell 
  - [ ] Bond 
  - [ ] Redeem

**Comment by KadenZipfel** [comment]
Implemented in: https://github.com/protofire/omen-exchange/pull/1851

**Pull request closed without merging**
