### PR TITLE
Display valid and invalid markets by default

### PR DESCRIPTION
**Pull request by KadenZipfel**
Closes https://github.com/protofire/omen-exchange/issues/1099

### CODE REVIEW

**Comment by pimato** [comment]
It looks like the filter component gets removed once the user picks `Market Validity - ALL` or `Market Validity - Valid` but not on `Market Validity - Invalid`.

We should in general keep the filter component visible once the user picks an item on any dropdown

**Review by pimato — CHANGES_REQUESTED** [review]
Please check comments

**Comment by KadenZipfel** [comment]
> It looks like the filter component gets removed once the user picks `Market Validity - ALL` or `Market Validity - Valid` but not on `Market Validity - Invalid`.
> 
> We should in general keep the filter component visible once the user picks an item on any dropdown

The problem with that approach is that the advanced filters will be always be open, even on initial page load. It's also worth noting that the other filters only stay open if the selected item is not 'All', so I've done the same for the market validity in this most recent commit.

**Comment by pimato** [comment]
Hey @KadenZipfel , there is a bug with the pagination:

1. launch omen locally
2. click on the filter button
3. pick on the `market validity - dropdown` => `Valid`
4. pick on the `market validity - dropdown` => `Invalid`
5. pick on the `market validity - dropdown` => `All`
6. BUG: pagination does not work anymore

**Comment by KadenZipfel** [comment]
> Regarding the collapse of the filter components once the user clicks on `All`. Is there really no way to keep the component collapsed? It kind a breaks the UX as we indicate the user that the component stays collapse on basically everything else besides `All`. How much work would it require?

Got it setup. Currently the advanced filters will be collapsed on page load if the selection is 'All', otherwise they will be open on page load. Additionally, all filters will stay open for any selection.

**Review by pimato — APPROVED** [review]

**Pull request closed without merging**
