### PR TITLE
Replace old tooltip components with react tooltip hook + new design

### PR DESCRIPTION
**Pull request by gem1no**
#1897 

image
image
image
image

### CODE REVIEW

**Review by pimato — CHANGES_REQUESTED** [review]
It looks like the tooltip has double borders?
Bildschirmfoto 2021-06-01 um 13 33 51

comparing with:
Bildschirmfoto 2021-06-01 um 13 36 00

**Comment by pimato** [comment]
can we add a comma in the time description tooltip like this:
```June 3rd 2021 - 14:30:00 CEST, Ends in 2 days```

**Comment by pimato** [comment]
looks like something is now broken with the pool liquidity data structure:
Bildschirmfoto 2021-06-01 um 13 40 00

compared to master:
Bildschirmfoto 2021-06-01 um 13 38 34

**Comment by pimato** [comment]
I am still not sure why there have been changes made in the pool section, but there are still styling changes which need to be corrected:

master:
Bildschirmfoto 2021-06-07 um 13 43 05

this PR:
Bildschirmfoto 2021-06-07 um 13 44 29

why did we add margins here?

**Review by pimato — CHANGES_REQUESTED** [review]
see comments

**Review by Mi-Lan — CHANGES_REQUESTED** [review]
Found one in funding_and_fee_step
Screenshot 2021-06-08 at 12 07 39
...Also one tip for the tooltips is that you just modify the react_tooltip_styles_override file since we are getting all tooltip classes from there.
Screenshot 2021-06-08 at 12 09 56

**Comment by gem1no** [comment]
> Found one in funding_and_fee_step
> Screenshot 2021-06-08 at 12 07 39
> ...Also one tip for the tooltips is that you just modify the react_tooltip_styles_override file since we are getting all tooltip classes from there. That way you will make sure not to miss any
> Screenshot 2021-06-08 at 12 09 56

hey thanks for the review. i'm not sure how youre seeing that, i made sure to address this tooltip.
my funding_and_fee_step screen: 
image

what browser are you on?

**Comment by Mi-Lan** [comment]
> > Found one in funding_and_fee_step
> > Screenshot 2021-06-08 at 12 07 39
> > ...Also one tip for the tooltips is that you just modify the react_tooltip_styles_override file since we are getting all tooltip classes from there. That way you will make sure not to miss any
> > Screenshot 2021-06-08 at 12 09 56
> 
> hey thanks for the review. i'm not sure how youre seeing that, i made sure to address this tooltip.
> my funding_and_fee_step screen:
> image
> 
> what browser are you on?

Ohh yeah now that I checked it again it works!

**Review by Mi-Lan — CHANGES_REQUESTED** [review]
Also not sure if this is how it's supposed to be but seems that tooltip on fee is transparent now...is it supposed to be that way? @pimato 
Screenshot 2021-06-18 at 13 37 55
Also I noticed that we have some unusued tooltip component and styles in react tooltip syles overrides....  would be good to clean that up maybe here or in new issue...

**Comment by gem1no** [comment]
> Also not sure if this is how it's supposed to be but seems that tooltip on fee is transparent now...is it supposed to be that way? @pimato
> Screenshot 2021-06-18 at 13 37 55
> Also I noticed that we have some unusued tooltip component and styles in react tooltip syles overrides.... would be good to clean that up maybe here or in new issue...

no, it's not supposed to be. seems like a known issue with react-tooltip that isn't solved. https://github.com/react-component/tooltip/issues/215

**Comment by gem1no** [comment]
not really sure why it's specifically this tooltip causing this bug, let me read more tonight

**Review by pimato — CHANGES_REQUESTED** [review]
lets change all tooltip border colors to: 
```border: 1px solid #E8EAF6;```

and give it a dropshadow:
```box-shadow: 0px 0px 4px #EBEBEB;```

**Review by pimato — APPROVED** [review]
looks good!

**Review by pimato — APPROVED** [review]
looks good!

**Review by KadenZipfel — APPROVED** [review]
LGTM!

**Pull request merged**
