### PR TITLE
Curated filtering

### LINKED ISSUE #1037: Filter markets by DxDao curated status
Part of #837

### PR DESCRIPTION
**Pull request by mariano-aguero**
Closes #1037

### CODE REVIEW

**Comment by hpmaxi** [comment]
@pimato This still needs some valid markets to test it correctly.

**Comment by KadenZipfel** [comment]
Looks like the advanced filters are open by default, I assume this is because valid is selected by default. Maybe let's not display the advanced filters unless invalid is selected.

**Comment by KadenZipfel** [comment]
LGTM. Marking this as a draft until we get all the stylistic bits setup (the blue checkmark for valid markets and the pending verification warning for invalid markets). I'm happy to handle that. 

I also think we should have an option to show all markets, valid & invalid. @pimato wdyt?

**Comment by pimato** [comment]
> I also think we should have an option to show all markets, valid & invalid. @pimato wdyt?

Correct! Check out my designs: https://www.figma.com/file/GNoehJ64fqfptghsjYqvTJ/Playground-V2?node-id=3426%3A0

**Review by pimato — APPROVED** [review]

**Pull request merged**
