### PR TITLE
Consolidate market_sell and scalar_market_sell component

### PR DESCRIPTION
**Pull request by Mi-Lan**
In this pr I merge market_sell and scalar market_sell shared logic into the MarketSellContainer component, located in pages folder.
Test:
- [ ] Scalar market sell and categorical market sell works as it should 
- [ ] Transaction states work good

### CODE REVIEW

**Review by hexyls — COMMENTED** [review]
Looking good!

on the scalar market I was unable to sell some shares, I had 0.3 shares and was trying to sell less than that, do you get this too?

Screen Shot 2021-07-29 at 5 22 46 pm

**Comment by Mi-Lan** [comment]
> Looking good!
> 
> on the scalar market I was unable to sell some shares, I had 0.3 shares and was trying to sell less than that, do you get this too?
> 
> Screen Shot 2021-07-29 at 5 22 46 pm

Nice catch! Dunno how it slipped up. I was issue with using two different indexed interchangeably. Should work now!

**Review by hexyls — APPROVED** [review]
🙌

**Comment by pimato** [comment]
Test:
- [ ] Scalar market sell and categorical market sell works as it should 
- [ ] Transaction states work good

**Review by pimato — APPROVED** [review]
works!

**Review by KadenZipfel — APPROVED** [review]
Looks good!

**Review by KadenZipfel — APPROVED** [review]
Looks good!

**Pull request merged**
