### PR TITLE
fix/1922

### PR DESCRIPTION
**Pull request by hexyls**
closes https://github.com/protofire/omen-exchange/issues/1922

### CODE REVIEW

**Review by Mi-Lan — APPROVED** [review]
Looks good! Besides SEO is there some other use for helmet? I was just reading up on it couldn't figure it out....

**Review by KadenZipfel — APPROVED** [review]
🔥

**Review by gem1no — APPROVED** [review]
LGTM

**Review by pimato — APPROVED** [review]
works!

**Pull request merged**
