### PR TITLE
fix max sell errors

### PR DESCRIPTION
**Pull request by hexyls**
closes https://github.com/protofire/omen-exchange/issues/1757 https://github.com/protofire/omen-exchange/issues/1676

There were clues in the code comments for how to resolve this, I tried to see if there was a better way but ultimately just kept the original solution mentioned.

### CODE REVIEW

**Review by KadenZipfel — APPROVED** [review]
🔥

**Review by pimato — APPROVED** [review]
works!

**Comment by pimato** [comment]
lets connect the rounding fix with this issue: https://github.com/protofire/omen-exchange/issues/1739
redeem not working! Should round down the amount to redeem too.

**Comment by pRoy24** [comment]
I think this may cause precision errors if the result has more decimals also would not work if precision error is more than a factor of 99999/100000 
Please checkout this alternative solution I propose and let me know if this works
https://github.com/protofire/omen-exchange/pull/1767

**Comment by hexyls** [comment]
closing in favour of https://github.com/protofire/omen-exchange/pull/1761

**Pull request closed without merging**
