### PR TITLE
fix/1952

### PR DESCRIPTION
**Pull request by hexyls**
closes https://github.com/protofire/omen-exchange/issues/1952

Deployed a new gnosis safe mastercopy for xdai which allows us to safely remove hardcoded gas for xdai.

Edit: Redeployed and verified at [0x9C75A217AEA76663a9A37687606f099945eb0742](https://blockscout.com/xdai/mainnet/address/0x9C75A217AEA76663a9A37687606f099945eb0742/contracts). Please diff this contract with our [mainnet deployment](https://etherscan.io/address/0xCB2E9FA32603Cdc2740b82a9A67ED3e977C33416#code), they should be identical 🤙

### CODE REVIEW

**Comment by pimato** [comment]
I have just tried to replicate the same market from described in: https://github.com/protofire/omen-exchange/issues/1952 and it seems like something is broken.

Steps to replicate:
1. Create the same market described in here: https://github.com/protofire/omen-exchange/issues/1952
2. Once you click `Create Market` metamask is popping up requesting a signature
BUG: Being directly connected, a user should not sign a signature but actually sign a transaction:
Bildschirmfoto 2021-06-09 um 18 49 42

**Review by pimato — CHANGES_REQUESTED** [review]
see comments

**Comment by hexyls** [comment]
@pimato hmmm I wasn't able to reproduce the issue above, could you please review again and see if you get a different result?

**Review by pimato — CHANGES_REQUESTED** [review]
@hexyls looks like there is some issue:
Bildschirmfoto 2021-06-16 um 10 51 24

the build is also not working via github.

**Comment by hexyls** [comment]
bad merge 😫 fixed now 👍

**Review by Mi-Lan — APPROVED** [review]
Works good!

**Review by KadenZipfel — APPROVED** [review]
LGTM!

**Review by pimato — APPROVED** [review]

**Pull request merged**
