### PR TITLE
Fix: Font-size and margin on Settings and broken RPC

### PR DESCRIPTION
**Pull request by Frankaus**
closes https://github.com/protofire/omen-exchange/issues/2082

Changed the font-size to default (14px) in RPC endpoint and removed the margin-left of Settings in broken RPC

### CODE REVIEW

**Review by Mi-Lan — APPROVED** [review]
LGTM!

**Comment by pimato** [comment]
It looks like the emergency rpc modal has not the correct font:
Bildschirmfoto 2021-08-12 um 15 11 54

compared to the one in the `Your Connection Modal`:
Bildschirmfoto 2021-08-12 um 15 12 01

**Review by pimato — CHANGES_REQUESTED** [review]
see comment.

**Comment by pimato** [comment]
@Frankaus you missed out a few others:
Bildschirmfoto 2021-08-12 um 16 27 21

**Comment by Frankaus** [comment]
> @Frankaus you missed out a few others:
> Bildschirmfoto 2021-08-12 um 16 27 21
> 
> Bildschirmfoto 2021-08-12 um 16 27 17
> 
> Bildschirmfoto 2021-08-12 um 16 27 08

Seems to happen because it was not specified in the code before and so the browser applies a default font. I will look at all of them now and make sure to specify the font-family Roboto

**Review by pimato — CHANGES_REQUESTED** [review]
any clue why the dropdown in our normal dropdown is 40px height but the emergency rpc node modal has a dropdown with 42px height?

normal:
Bildschirmfoto 2021-08-17 um 13 54 40

emergency dropdown:
Bildschirmfoto 2021-08-17 um 13 54 49

**Comment by Frankaus** [comment]
> any clue why the dropdown in our normal dropdown is 40px height but the emergency rpc node modal has a dropdown with 42px height?
> 
> normal:
> Bildschirmfoto 2021-08-17 um 13 54 40
> 
> emergency dropdown:
> Bildschirmfoto 2021-08-17 um 13 54 49

because the height was never set on this box. Do you want it to be 40px or 42px?

**Comment by pimato** [comment]
> > any clue why the dropdown in our normal dropdown is 40px height but the emergency rpc node modal has a dropdown with 42px height?
> > normal:
> > Bildschirmfoto 2021-08-17 um 13 54 40
> > emergency dropdown:
> > Bildschirmfoto 2021-08-17 um 13 54 49
> 
> because the height was never set on this box. Do you want it to be 40px or 42px?

40px as we have it throughout the application.

**Review by hexyls — APPROVED** [review]
🙌

**Review by pimato — APPROVED** [review]

**Pull request merged**
