### PR TITLE
Fix prediction error by limiting decimals

### PR DESCRIPTION
**Pull request by hexyls**
closes https://github.com/protofire/omen-exchange/issues/2159

### CODE REVIEW

**Review by Mi-Lan — APPROVED** [review]
@hexyls Good job! Fixes it nicely 🚀

**Review by Frankaus — APPROVED** [review]
Screenshot 2021-08-09 at 12 54 35

I could create a scalar mkt (https://rinkeby.etherscan.io/tx/0xbb1d6bb8c19c8458dbcb6845a448052f4bb2fd51273c8228f68f86e10267d68e) and buy (https://rinkeby.etherscan.io/tx/0xf2ea63ee5b68c1986586a2c9b1abda1b54d54ad6f3d49d0df47cbacf7051e39b) without any error.

Works great, GJ!:)

**Review by pimato — APPROVED** [review]
Works great!

**Comment by Frankaus** [comment]
- [ ] Categorical markets
- [x]     Create market 
https://rinkeby.etherscan.io/tx/0x5a86f875e169f846073f0a161a4c238e98dd937b35a310b71c72c1b9b8125e97
- [x]     Buy 
https://rinkeby.etherscan.io/tx/0x9caecfc14a3f88596c7ff9db94868ed490a624eddf569a2b442701a49167bd9e
- [x]     Sell 
https://rinkeby.etherscan.io/tx/0x38b42edbb908d26c299d63415a32cde2d5cd02e4b56c8268785356fe8af7106a
- [x]     Deposit 
https://rinkeby.etherscan.io/tx/0x231759437272f78de9d83dde26efdc2df29ec2b03e57cb51af1c607db55c06aa
- [x]     Withdraw 
https://rinkeby.etherscan.io/tx/0x471a153dc415260288d77797ce163df8eb85062b0de2e23aff38a74880938551
- [x]     Bond outcome 
https://rinkeby.etherscan.io/tx/0xdf18e628bb81733517e34be0f023dfa49829644cd8ec66ededbc3404b74a31fa
- [ ]     Redeem winnings 
- [ ] Scalar markets
- [ ]     Create market 
- [ ]     Buy 
- [ ]     Sell 
- [ ]     Deposit 
- [ ]     Withdraw 
- [ ]     Bond outcome 
- [ ]     Redeem winnings 
- [ ]     Position table works as expected

- [ ]     Market buy slider works as expected

**Pull request merged**
