### PR TITLE
feature/guild

### PR DESCRIPTION
**Pull request by hexyls**
Testing:
- Airdrop on xdai tight integration works (I redeployed)
- Guild lock/unlock works on Rinkeby (you will need [rinkeby OMN](https://rinkeby.etherscan.io/address/0x0a08eca47c56c305f4feb4fa062aecd5807bebb8) to test)

If there are issues please dive in and try to resolve them, need to get this branch merged asap

### CODE REVIEW

**Comment by pimato** [comment]
- [ ] Airdrop on xdai tight integration works (I redeployed)
- [ ] Guild lock/unlock works on Rinkeby (you will need rinkeby OMN to test)

**Review by pimato — APPROVED** [review]
Looks good!

**Comment by Frankaus** [comment]
- [x] Categorical markets
- [x]     Create market 
https://rinkeby.etherscan.io/tx/0x5555413f3419b0524d07cc357f9b21e5106c53847b08e6ca718e7e3257644960
- [x]     Buy 
https://rinkeby.etherscan.io/tx/0xd9efe79f36b1dec6677cad56c6d1101629c0b32d380be87294ce8799b8d59655
- [x]     Sell 
https://rinkeby.etherscan.io/tx/0xfb1cbe3f0e6767845a17e967f261adf2631074b6791833266ce9ab9c2fd0668a
- [x]     Deposit 
https://rinkeby.etherscan.io/tx/0xe149eaefd0e4a738fcf6ac11f24aadfe21b17eebb59bebe4a424ad97f274f0cf
- [x]     Withdraw 
https://rinkeby.etherscan.io/tx/0xeb6454c4ea77454ae7d883d2e4aaeee3d01544ea4254f50121cb476f29303eab
- [x]     Bond outcome 
https://rinkeby.etherscan.io/tx/0x5fcff2ba574d3f0cca15ece288b436790c03cd12f756945860d6039ce8163121
- [x]     Redeem winnings 
https://rinkeby.etherscan.io/tx/0x3b6347943f5477a888704a595812d01c79adda6e57b0086c6e3387ec7ec8036d
- [ ] Scalar markets
- [x]     Create market 
https://rinkeby.etherscan.io/tx/0x68c494804f88279c370361ec5e5e534d18322485817b8308509875b9160b5ec9
- [x]     Buy 
https://rinkeby.etherscan.io/tx/0xaa86a95e381418502278dedc250380096e846e678693dc4695c239121625b53e
- [x]     Sell 
https://rinkeby.etherscan.io/tx/0x9b7adda536ebb2c9b7d8d17685897f57f36c18ec5d1c193357530a41c3a30431
- [x]     Deposit 
https://rinkeby.etherscan.io/tx/0x96a1467026e5173e346ec9f0c1ac8098da0078bc810be458454a5f89961de4e5
- [x]     Withdraw 
https://rinkeby.etherscan.io/tx/0x127e44f21242934384d4b0edbf861da253b4b828f9a21a33b350009cd91a3695
- [x]     Bond outcome 
https://rinkeby.etherscan.io/tx/0x21b4022d53e291125f6433ca9cc019f4bf23c61ddc921a20d5fbbda04c30983d
- [x]     Redeem winnings 
https://rinkeby.etherscan.io/tx/0xd88f04e4ae25c832e42310ed83c7be97c7f3d2bafc90f761b4c8df95df410598
- [x]     Position table works as expected

- [ ]     Market buy slider works as expected
- [ ]     Guild lock/unlock works on Rinkeby (you will need rinkeby OMN to test)

**Review by Mi-Lan — APPROVED** [review]
Works good! Nice job! Also one more thing not sure why I can't see claim transaction done through the xDai tight? Is it something blockscout related or? I did receive it though...
Screenshot 2021-08-11 at 13 03 23
https://blockscout.com/poa/xdai/tx/0x3c7c4bb691ca05a0626146161f2ac39e1bfcb6545cb4fe1bb8c47bc8b942a6a6

**Pull request merged**
