### PR TITLE
Feature/sokol

### PR DESCRIPTION
**Pull request by hexyls**
closes https://github.com/protofire/omen-exchange/issues/1408

How to play with this this atm:
1. Add Sokol as a new network to your wallet:
     Name: Sokol Test Network
     RPC: https://sokol.poa.network
     Chain ID: 77
     Symbol: SPOA
     Block explorer: https://blockscout.com/poa/sokol
2. Use https://faucet.poa.network/ while connected to Sokol to get SPOA
3. Send some SPOA to the wrapped SPOA address: 0xc655c6D80ac92d75fBF4F40e95280aEb855B1E87

### CODE REVIEW

**Comment by pimato** [comment]
works great so far!

**Comment by pimato** [comment]
looks like we have another new Kleros contract: 
https://blockscout.com/poa/sokol/address/0xf3Aaf8A99f1119d02Af9bBfEafA8a71dDD4c582e/contracts

**Review by pimato — DISMISSED** [review]
new contract

**Review by KadenZipfel — APPROVED** [review]
Seems to work flawlessly and the code looks solid 👏

**Review by Mi-Lan — APPROVED** [review]
Works great! Tested market creation, depositing and buy/sell.

**Review by pimato — APPROVED** [review]

**Pull request merged**
