### PR TITLE
Reduce bundle size a bit

### PR DESCRIPTION
**Pull request by hexyls**
related https://github.com/protofire/omen-exchange/issues/2026

Was only able to reduce the bundle size a tiny bit (2.6 MB -> 2.25 MB), probably wasn't worth the effort of digging through the deps tbh but we might as well keep what we got.

It would have been nice to remove [3box-comments-react](https://github.com/3box/3box-comments-react) which is quite large, maybe we can do that later when we update the comment section 🤔

Will keep https://github.com/protofire/omen-exchange/issues/2026 open because it is more of an ongoing thing we should always be thinking about, but we can remove it from the current milestone.

Testing: App works as expected

### CODE REVIEW

**Review by pimato — APPROVED** [review]
great work!

**Review by Mi-Lan — APPROVED** [review]
Looks good! Yeah I would also like to remove 3box! Cant wait for that....are we planning to replace it with ceramic or something like that?

**Comment by hexyls** [comment]
@Mi-Lan yeah ceramic would be super cool!

**Review by KadenZipfel — APPROVED** [review]
Looks good!

**Pull request merged**
