### PR TITLE
Restyle Buttons for the whole project #1267

### PR DESCRIPTION
**Pull request by liaojikunwork**

### CODE REVIEW

**Comment by pimato** [comment]
The Circle button should have 40x40, currently:
Bildschirmfoto 2020-11-10 um 17 27 29

**Comment by pimato** [comment]
The icon inside the filter button increased to 24px, but currently:
Bildschirmfoto 2020-11-10 um 17 34 15

[Figma design specification](https://www.figma.com/file/R056tSYMjvfwaFidEBItYy/Widgets-V2?node-id=1209%3A141):
Bildschirmfoto 2020-11-10 um 17 34 55

**Comment by pimato** [comment]
the search icon is not correct according to my design specification, currently:
Bildschirmfoto 2020-11-10 um 17 39 37

should look like, (icon 24x24px):
Bildschirmfoto 2020-11-10 um 17 40 15

**Comment by pimato** [comment]
Bildschirmfoto 2020-11-10 um 17 46 19

connect button has wrong paddings

**Review by pimato — CHANGES_REQUESTED** [review]
see comments

**Comment by pimato** [comment]
also the add button in the create process:
Bildschirmfoto 2020-11-10 um 17 55 23

Bildschirmfoto 2020-11-10 um 17 56 41

add icon has 12x12px in my design specification it has 14x14px with a total svg size of 24x24px. 
[Design Specification](https://www.figma.com/file/R056tSYMjvfwaFidEBItYy/Widgets-V2?node-id=1209%3A141)

**Comment by Mi-Lan** [comment]
looks good ! Except changes geronimo found i couldn't catch anything....

**Comment by pimato** [comment]
the big circle arrow button back has still a 20px icon:
Bildschirmfoto 2020-11-11 um 10 32 27

but should:
Bildschirmfoto 2020-11-11 um 10 33 07

**Comment by pimato** [comment]
can we make those connection buttons to default height of 40px:
Bildschirmfoto 2020-11-11 um 10 34 12

**Review by pimato — CHANGES_REQUESTED** [review]
see comments

**Review by Mi-Lan — CHANGES_REQUESTED** [review]
@liaojikunwork height of the arrow button still needs to be changed

**Review by Mi-Lan — APPROVED** [review]
LGTM!

**Review by pimato — APPROVED** [review]

**Review by KadenZipfel — APPROVED** [review]

**Pull request merged**
