### PR TITLE
Mainnet <> xDai

### PR DESCRIPTION
**Pull request by KadenZipfel**
Closes: https://github.com/protofire/omen-exchange/issues/1550

To test locally, checkout `451fd71` and spin up `localhost:3000` and `localhost:3001` at the same time.

### CODE REVIEW

**Comment by pimato** [comment]
Did some simple testing and works great so far!

**Review by hexyls — APPROVED** [review]
This is great 🙌

**Comment by pimato** [comment]
works great :)

**Review by pimato — APPROVED** [review]

**Review by Mi-Lan — APPROVED** [review]
Very cool feature! Only thing i could suggest is different background message instead of Market not found since we know that it is because of wrong network we can be more specific.
Screenshot 2021-01-20 at 11 34 26

**Comment by KadenZipfel** [comment]
> Very cool feature! Only thing i could suggest is different background message instead of Market not found since we know that it is because of wrong network we can be more specific.
> Screenshot 2021-01-20 at 11 34 26

Good call! I'll put together an issue for this

**Pull request merged**
