### PR TITLE
fix meta tags

### PR DESCRIPTION
**Pull request by hexyls**
closes https://github.com/protofire/omen-exchange/issues/1707 and https://github.com/protofire/omen-exchange/issues/1736

Hardcoded metatags and removed react-helmet just for the initial load. React-helmet will still update individual market pages on the fly.

Also added a new 2:1 ratio Omen logo so the logo is fully visible on social media. Shares on twitter and facebook should look like:

Screen Shot 2021-04-09 at 2 55 13 pm

### CODE REVIEW

**Review by gem1no — APPROVED** [review]
LGTM

**Comment by KadenZipfel** [comment]
I like how the image has a transparent background so it looks super cool on dark mode 👀
image

**Review by KadenZipfel — APPROVED** [review]
Much needed, and well executed!

**Review by Mi-Lan — APPROVED** [review]
Looks good! Would be good if we can somehow test, how it will look on google before releasing...

**Pull request merged**
