### PR TITLE
refactor: remove compound logic from market sell

### PR DESCRIPTION
**Pull request by hexyls**
related https://github.com/protofire/omen-exchange/issues/2012 

This PR removes compound logic from both categorical and scalar market sells.

Additional change - Wrapped assets are always unwrapped when selling, e.g. WETH -> ETH, to match changes in the previous PR.

if we merge https://github.com/protofire/omen-exchange/pull/2027 first it will be easier to see the changes in this PR

Testing:
- [ ] DAI categorical market sell - works, UI looks normal
- [ ] DAI scalar market sell - works, UI looks normal
- [ ] ETH categorical market sell - works, UI looks normal
- [ ] ETH scalar market sell - works, UI looks normal, WETH unwrapped

### CODE REVIEW

**Review by Mi-Lan — APPROVED** [review]
Tested all the cases! Works on all of them! Great job!

**Comment by KadenZipfel** [comment]
Testing:
- [ ] DAI categorical market sell - works, UI looks normal
- [ ] DAI scalar market sell - works, UI looks normal
- [ ] ETH categorical market sell - works, UI looks normal
- [ ] ETH scalar market sell - works, UI looks normal, WETH unwrapped

**Review by KadenZipfel — APPROVED** [review]
LGTM!

**Comment by pimato** [comment]
Testing:
- [x] DAI categorical market sell - works, UI looks normal
- [x] DAI scalar market sell - works, UI looks normal
- [x] ETH categorical market sell - works, UI looks normal
- [x] ETH scalar market sell - works, UI looks normal, WETH unwrapped

**Review by pimato — APPROVED** [review]

**Pull request merged**
