### PR TITLE
Add airdrop for DXD holders

### PR DESCRIPTION
**Pull request by hexyls**
related https://github.com/protofire/omen-exchange/issues/2093

PR adds a rinkeby airdrop for the weighted dxd snapshot ([script is here](https://github.com/hexyls/omen-airdrop/blob/master/dxd.js))

Testing: When you claim you should receive two airdrops like this [example transaction](https://rinkeby.etherscan.io/tx/0xff77ba5f9b45d65c78f1eb42ea4e70337a5bef228be75f435f069434346c55be)

Just a reminder of testing addresses:
@pimato: 0x81a94868572ea6e430f9a72ed6c4afb8b5003fdf
@KadenZipfel: 0x3111327edd38890c3fe564afd96b4c73e8101747
@Mi-Lan: 0x11aa7ef6d9fb561b2050c90f655286ea2409a477
@Frankaus: 0x4502166be703312eae5137ad7399393b09471f27

### CODE REVIEW

**Review by pimato — CHANGES_REQUESTED** [review]
Hey @hexyls it looks like @luzzif has been working on a more complete version of the airdrop script which should include way more DXD holders which have been using DXD in contracts: https://github.com/luzzif/swapr-token-contracts/tree/master/whitelist-creation/dxd-holders

We should use the same updated script.

For example I just checked my address and did not receive DXD mainly because they are locked in a liquidity reward contract on SWAPR.

**Comment by hexyls** [comment]
@pimato yeah the @luzzif script is definitely superior (and the code is amazing btw), I have incorporated some of his work into the script for this PR - we can fully migrate to using only his script if we decide not to do a weighted drop but just a holder snapshot drop, what do you think?

**Comment by luzzif** [comment]
Hey guys, I will need to make the script balance-weighted too soon, so you could just wait a bit until I implement the logic that way.

**Comment by pimato** [comment]
> Hey guys, I will need to make the script balance-weighted too soon, so you could just wait a bit until I implement the logic that way.

Sounds awesome. @hexyls lets wait for @luzzif balance-weighted changes and we should be good to go.

**Comment by luzzif** [comment]
Just pushed the balance-weighted update. I've also taken into consideration Uniswa v3 LPs, which added an account to the overall whitelist. As of now, I'm taking into consideration Honeyswap LPs, Balancer v1 LPs, Loopring holders, Mesa depositors, Swapr LPs on both mainnet and xDai (including people that staked their LP token in a farm) and Uniswa v2/v3 LPs, apart from the "normal" holders (i.e. people that hold DXD in their address without putting it to work). I think it's a comprehensive enuogh list. I'm excluding vested DXD beneficiaries (i.e. DXdao workers), because they will have a separate airdrop. What do you guys think?

**Comment by hexyls** [comment]
Awesome and super thorough, thanks @luzzif - will you upload updated cache files?

**Comment by hexyls** [comment]
Changes are:

1. After a discussion with @KadenZipfel about how we can simplify the airdrops - Both the Omen user airdrop and the DXD holder airdrops are happening to xdai tight integration accounts. This adds an extra stickiness too because users will have to onboard into an Omen account to claim their airdrop.
2. For testing we are using the same TEST token across [mainnet](https://etherscan.io/token/0xa7370f2a5afaa987492cd0f5c0fe14191c70aaa5) and [xdai](https://blockscout.com/xdai/mainnet/tokens/0xF52eAbb903831E2026a6A50Ce813fc871B5578f4/token-transfers)
3. Instead of loading up huge json files in the frontend we are fetching individual claim information [from github](https://github.com/hexyls/omen-airdrop/tree/master/1)

**Review by Frankaus — COMMENTED** [review]
Screenshot 2021-08-10 at 10 03 48

Screenshot 2021-08-10 at 14 43 31

Screenshot 2021-08-10 at 14 45 04

https://rinkeby.etherscan.io/tx/0xfa65432e6ea784cf34ba26a8366d771a0e38731b0d55ef15e58311630f0a9521

I could claim and I redeemed my 3,846.153 OMN/TST properly, however this was done on rinkeby, not xdai network. The modal triggered automatically when I connected the wallet.

**Review by KadenZipfel — APPROVED** [review]
Works well and LGTM!

**Review by Mi-Lan — COMMENTED** [review]
I couldn't test the airdrop unfortunately. Since I already claimed mine before....

**Review by pimato — APPROVED** [review]
works great!

**Pull request merged**
