### PR TITLE
Check number of winning shares for scalar market

### PR DESCRIPTION
**Pull request by KadenZipfel**
Closes: https://github.com/protofire/omen-exchange/issues/1749

### CODE REVIEW

**Review by Mi-Lan — COMMENTED** [review]
Tested on market where i have winning outcome. And it works! Will check tomorrow for market where i didn't win. Then i'm approving!
This pr:
Screenshot 2021-03-19 at 00 31 40
Master:
Screenshot 2021-03-19 at 00 31 34
Would be good if we test invalid markets as well...

**Comment by Mi-Lan** [comment]
Seems that line is missing above resolve condition maybe? Couldn't find it in figma...

**Comment by pimato** [comment]
Could we get the border back between the winning/loosing message and the button navigation?
Bildschirmfoto 2021-03-19 um 11 56 01

**Review by pimato — CHANGES_REQUESTED** [review]
see comment

**Comment by Mi-Lan** [comment]
@KadenZipfel hope you don't mind me meddling with your pr...i synced with geronimo on this so we get the release done asap...

**Review by Mi-Lan — APPROVED** [review]
Tested couple more use cases! And it looks good!

**Comment by pimato** [comment]
@Mi-Lan there is no need for padding-left and right here:
Bildschirmfoto 2021-03-19 um 21 06 13

**Comment by Mi-Lan** [comment]
@pimato Added fix

**Review by pimato — APPROVED** [review]

**Review by hexyls — APPROVED** [review]

**Pull request merged**
