### PR TITLE
Max Button does not work with USDC and higher balance #1270

### PR DESCRIPTION
**Pull request by liaojikunwork**
Screen Shot 2020-11-02 at 8 31 51 AM

### CODE REVIEW

**Review by pimato — APPROVED** [review]

**Review by Mi-Lan — COMMENTED** [review]
Screenshot 2020-11-02 at 16 48 46
@pimato should we maybe limit decimals on max amount? Since all the other numbers are rounded to 2 or 5?

**Comment by liaojikunwork** [comment]
> Screenshot 2020-11-02 at 16 48 46
> @pimato should we maybe limit decimals on max amount? Since all the other numbers are rounded to 2 or 5?

@Mi-Lan  Decimals point depends on Token.
And that's an inputField, so I should show the correct number.

What is your thought? @pimato

**Comment by pimato** [comment]
I agree @Mi-Lan. @liaojikunwork could we show in the frontend 5 decimals but in the background actually use the full decimals?

**Review by pimato — CHANGES_REQUESTED** [review]
see comment.

**Comment by liaojikunwork** [comment]
> I agree @Mi-Lan. @liaojikunwork could we show in the frontend 5 decimals but in the background actually use the full decimals?

@pimato , can't show the front 5 decimals only.
Each token has its decimal points.

For cDai, it's 2.
So I can show only the front 2 decimals.

Is it ok?

**Comment by liaojikunwork** [comment]
Each token has its own decimal points.
About cDai, it's 2.
@pimato  What about showing the front 2 or 5 decimal points? (depends on token)

**Comment by liaojikunwork** [comment]
Screen Shot 2020-11-02 at 11 44 19 AM
Screen Shot 2020-11-02 at 11 44 33 AM
Screen Shot 2020-11-02 at 11 44 42 AM

**Review by Mi-Lan — APPROVED** [review]
LGTM!

**Comment by KadenZipfel** [comment]
Should be updated in the create market funding component as well if not already done

**Review by KadenZipfel — APPROVED** [review]

**Review by KadenZipfel — CHANGES_REQUESTED** [review]
See comment

**Review by pimato — APPROVED** [review]

**Review by KadenZipfel — APPROVED** [review]

**Pull request merged**
