### PR TITLE
add fix for issue 1649

### PR DESCRIPTION
**Pull request by pRoy24**
Fixes https://github.com/protofire/omen-exchange/issues/1649

### CODE REVIEW

**Review by hexyls — APPROVED** [review]
🎉

**Comment by pimato** [comment]
Buy shares amount is inconsistent with the buy form, if buying with cTokens:
Bildschirmfoto 2021-02-15 um 08 22 39

**Review by pimato — CHANGES_REQUESTED** [review]
see comment

**Comment by pRoy24** [comment]
> see comment

yup good catch, the shares popup need to be in base collateral regardless of whether the base or cToken is chosen.

**Review by pimato — APPROVED** [review]

**Review by Mi-Lan — APPROVED** [review]

**Pull request merged**
