### PR TITLE
Fix/#1780

### PR DESCRIPTION
**Pull request by hexyls**
Closes https://github.com/protofire/omen-exchange/issues/1780

Other changes in relay mode:
- Removes all mention of wxDai
- Shows only dai markets (STAKE markets shouldn’t show up)
- Removes unwrapping UI for categorical sell/withdraw. What I mean by this is that because we are removing references to wxDai on the relay we don't need to show an option for the user in the UI to choose between receiving wxDai or xDai (because we just default to xDai)

### CODE REVIEW

**Comment by KadenZipfel** [comment]
Code looks solid! Here are some places that still need updating:

- Transaction details not updated
    - 
- Still possible to fund markets with various tokens
    - 
- Fund market currency selector displays xDai
    -

**Comment by Mi-Lan** [comment]
@hexyls Ohh man big undertaking! Found one more Kaden sniffed them out good
Screenshot 2021-03-29 at 22 24 40

**Comment by hexyls** [comment]
lol why is this of all things so freaking hard 😄 I thiiinnnkkk I got it this time but I won't be surprised if I missed something 🤞

**Review by Mi-Lan — APPROVED** [review]
Nice work! Couldn't find any now

**Comment by Mi-Lan** [comment]
@hexyls found one more! 
Screenshot 2021-03-30 at 17 05 45

**Review by Mi-Lan — APPROVED** [review]
GJ!

**Review by KadenZipfel — APPROVED** [review]
LGTM!

**Review by pimato — APPROVED** [review]
works great! :)

**Pull request merged**
