### PR TITLE
remove authereum login option on xdai

### PR DESCRIPTION
**Pull request by hexyls**
as mentioned on keybase authereum does not support xDai so gotta hide it on the xdai subdomain.

### CODE REVIEW

**Review by pRoy24 — COMMENTED** [review]
It still shows up as an option when on localhost when connected to xdai network and will also show up as an option on https://xdai.dxtest.eth.link/ Wondering if there is a better way to detect the current provider RPC URL in window context and disable based on that.

**Review by Mi-Lan — CHANGES_REQUESTED** [review]
I agree with roy..but maybe we can just add additional locations with "OR" statment and cover all the cases ....

**Review by Mi-Lan — APPROVED** [review]
Screenshot 2021-02-11 at 13 05 43
works good!

**Review by KadenZipfel — APPROVED** [review]
👌

**Review by pimato — APPROVED** [review]

**Pull request merged**
