### PR TITLE
Use scaled fields from subgraph

### LINKED ISSUE #865: Filtering by high liquidity is not working
Filtering by high volume is not working.
[This market](https://dxtest.eth.link/#/0x592af74865799e1ed509afef002a6eca26e1caa2 ) has 50k funding but when I list markets sorted by liquidity it doesnt show up.

The my markets filter also doesn’t work  right now

### LINKED ISSUE #867: Volumes are not correct
Somehow also volumes are not correct: This market has $700 volume. but doesn’t show up here with the correct volume in the overview section. https://dxtest.eth.link/#/0x592af74865799e1ed509afef002a6eca26e1caa2

To take into account : 
My Markets shows the ones you created or funded, not where you buy the outcomes , the volumes issue could be a subgraph problem

### LINKED ISSUE #923: 24h volume sorting doesn`t seem to work properly
Screenshot 2020-07-11 at 12 02 11

### LINKED ISSUE #928: usdc decimals buy order numbers way too high
Screenshot 2020-07-12 at 03 10 13

### PR DESCRIPTION
**Pull request by hpmaxi**
Closes #867 
Closes #928 
Closes #923 
Closes #865

### CODE REVIEW

**Comment by pimato** [comment]
Hey @hpmaxi , seems like https://github.com/protofire/omen-exchange/issues/928 wasn´t fixed as I still see:

for buy:
Screenshot 2020-07-13 at 19 34 15

for sell:
Screenshot 2020-07-13 at 19 34 33

for liquidity provision:
Screenshot 2020-07-13 at 19 34 40

**Comment by pimato** [comment]
Also, I hoped this: https://github.com/protofire/omen-exchange/issues/923 would be fixed with the new subgraph fix but:

Screenshot 2020-07-13 at 19 38 38

the first item shows 0.00 DAI volume

**Comment by hpmaxi** [comment]
@pimato Can you check again please

**Comment by pimato** [comment]
@pimato what exactly? it looks still the same.

**Comment by pimato** [comment]
@hpmaxi buy/sell seems fixed, but the fee in the liquidity provision is still the same

**Comment by pimato** [comment]
Looks like https://github.com/protofire/omen-exchange/issues/867 and https://github.com/protofire/omen-exchange/issues/928 is fixed!

**Comment by pimato** [comment]
do you know what is going on with https://github.com/protofire/omen-exchange/issues/923 ?

**Comment by hpmaxi** [comment]
I think is related to sorting by `lastActiveDayAndScaledRunningDailyVolume` that is the product of the last day active with his daily volume, but for showing it we need to use `runningDailyVolume` and format it inside the app, so I guess that it could seem unordered because of `lastActiveDay` being different across markets.

**Comment by pimato** [comment]
but shouldn`t  the first market be not at the top based on your assumption?
Screenshot 2020-07-13 at 20 58 27

if it would be sorted, it should be below the second item right?

**Comment by hpmaxi** [comment]
@pimato Yes, seems to be a precision problem in the graph, Alan opened an issue about it. 
I add another commit for #865

**Comment by pimato** [comment]
@hpmaxi looks like the subgraph (https://thegraph.com/explorer/subgraph/cag/omen) has been synced with the new fixes but it still looks like something is wrong with 24h sorting:
Screenshot 2020-07-14 at 12 02 52

**Pull request merged**
