### PR TITLE
wait for subgraph to sync after submitAnswer

### PR DESCRIPTION
**Pull request by hexyls**
Fixes an issue where the UI would not always update after bonding an answer on any non-relay networks.

### CODE REVIEW

**Review by Mi-Lan — CHANGES_REQUESTED** [review]
Great job! Its already much better but seems that it still takes some time to update it...

https://user-images.githubusercontent.com/33226956/115382345-dbefda00-a1d4-11eb-977e-2e67298fcdd4.mov
(Dunno why my whole screen is recorded...

**Comment by hexyls** [comment]
Good point and good catch @Mi-Lan!

I moved things around so the tx confirmation doesn't happen until after subgraph sync 👍

**Review by pimato — APPROVED** [review]
works perfect!

**Review by Mi-Lan — APPROVED** [review]
This is it man! Great work! Heres one more Rinkeby market i have left if someone else want to test it http://localhost:3000/#/0x0aeeebe923434f7a6b874d59d1a2a66afc7a1655

**Pull request merged**
