### PR TITLE
small fixes

### PR DESCRIPTION
**Pull request by Mi-Lan**
some heavy duty tasks ! issues https://github.com/protofire/omen-exchange/issues/1113 https://github.com/protofire/omen-exchange/issues/1109

### CODE REVIEW

**Comment by pimato** [comment]
To have a consistent terminology we should replacing `Ending` with `Closing`.

For that:
Bildschirmfoto 2020-10-06 um 20 36 01
Should be `Closing soon`

**Comment by pimato** [comment]
also this: 
Bildschirmfoto 2020-10-06 um 20 37 51

Instead of:

**Comment by pimato** [comment]
issue https://github.com/protofire/omen-exchange/issues/1109 looks to be fixed!

**Review by pimato — CHANGES_REQUESTED** [review]
see comments

**Review by KadenZipfel — APPROVED** [review]

**Review by pimato — APPROVED** [review]

**Pull request merged**
