### PR TITLE
Properly track liquidity

### PR DESCRIPTION
**Pull request by KadenZipfel**
Closes: https://github.com/protofire/omen-exchange/issues/2066

Testing: 
Can test by going to etherscan for market and checking `totalSupply`
- [ ] List item view
- [ ] Market details
    - [ ] Open market
    - [ ] Closed market
- [ ] Scalar market pool view
    - [ ] Your liquidity
        - Should be equal to the amount you receive for withdrawing max
- [ ] Categorical market pool view
    - [ ] Your liquidity
        - Should be equal to the amount you receive for withdrawing max
- [ ] Anywhere else?

### CODE REVIEW

**Review by hexyls — APPROVED** [review]
Looks good!

- [x] List item view
- [x] Market details
    - [x] Open market
    - [x] Closed market
- [x] Scalar market pool view
    - [x] Your liquidity
        - Should be equal to the amount you receive for withdrawing max
- [x] Categorical market pool view
    - [x] Your liquidity
        - Should be equal to the amount you receive for withdrawing max

**Comment by pimato** [comment]
Testing: 
Can test by going to etherscan for market and checking `totalSupply`
- [ ] List item view
- [ ] Market details
    - [ ] Open market
    - [ ] Closed market
- [ ] Scalar market pool view
    - [ ] Your liquidity
        - Should be equal to the amount you receive for withdrawing max
- [ ] Categorical market pool view
    - [ ] Your liquidity
        - Should be equal to the amount you receive for withdrawing max
- [ ] Anywhere else?

**Review by pimato — APPROVED** [review]
works great!

**Comment by Mi-Lan** [comment]
- [ ] List item view
- [ ] Market details
    - [ ] Open market
    - [ ] Closed market
- [ ] Scalar market pool view
    - [ ] Your liquidity
        - Should be equal to the amount you receive for withdrawing max
- [ ] Categorical market pool view
    - [ ] Your liquidity
        - Should be equal to the amount you receive for withdrawing max
- [ ] Anywhere else?

**Review by Mi-Lan — APPROVED** [review]
Gj! Wasn't aware that liquidity was off by this much in some cases!

**Pull request merged**
