### PR TITLE
Wait for transaction before navigating to new scalar market

### PR DESCRIPTION
**Pull request by KadenZipfel**
Closes https://github.com/protofire/omen-exchange/issues/1443

### CODE REVIEW

**Review by pimato — APPROVED** [review]
works!

**Review by pimato — APPROVED** [review]

**Review by hexyls — APPROVED** [review]
Subgraph is still busted so can't fully test but there is no reason this wouldn't work 👍

**Review by Mi-Lan — CHANGES_REQUESTED** [review]
@KadenZipfel hmmm for me it seems not to work...when i create market and transaction gets confirmed it seems not to catch that and loader for creating market seems just to sit there indefinitely....

**Review by Mi-Lan — APPROVED** [review]
@KadenZipfel didn't know that i needed to have kadenzipfel/omen-rinkeby that subgraph....so when i used that one it worked like charm! GJ

**Pull request merged**
