### PR TITLE
Increase rounding precision

### PR DESCRIPTION
**Pull request by KadenZipfel**
Closes: https://github.com/protofire/omen-exchange/issues/1766

Testing:
- [ ] Max sell works
  - [ ] Including low decimal tokens, e.g. USDC
- [ ] Redeem works
  - [ ] Including low decimal tokens, e.g. USDC

### CODE REVIEW

**Review by hexyls — APPROVED** [review]
Testing:
- [x] Max sell works
  - [x] Including low decimal tokens, e.g. USDC
- [x] Redeem works
  - [x] Including low decimal tokens, e.g. USDC

**Comment by Mi-Lan** [comment]
Testing:
- [ ] Max sell works
  - [ ] Including low decimal tokens, e.g. USDC
- [ ] Redeem works
  - [ ] Including low decimal tokens, e.g. USDC

**Review by Mi-Lan — APPROVED** [review]
Works! Although didn't test usdc since i didn't have any....

**Comment by pimato** [comment]
Testing:
- [ ] Max sell works
  - [ ] Including low decimal tokens, e.g. USDC
- [ ] Redeem works
  - [ ] Including low decimal tokens, e.g. USDC

**Review by pimato — APPROVED** [review]
works great!

**Pull request merged**
