### PR TITLE
Liquidity Rewards UI

### PR DESCRIPTION
**Pull request by gem1no**
#1869

### CODE REVIEW

**Review by pimato — CHANGES_REQUESTED** [review]
Great work!

After seeing my design changes life, I think it would be better if we put Current APY to the top of the liquidity rewards column:
Bildschirmfoto 2021-05-17 um 22 12 52

**Comment by pimato** [comment]
the Header of the column has pure black as the color:
Bildschirmfoto 2021-05-17 um 22 14 37

Design specification says `#37474F`

**Comment by pimato** [comment]
Why do we have the margin-right: 5px here?
Bildschirmfoto 2021-05-17 um 22 15 59

(looks like it is not new code?)

**Review by pimato — CHANGES_REQUESTED** [review]
Now that we have the `<0.01` Indicator I think we should remove the `+` here:
Bildschirmfoto 2021-05-18 um 10 06 48

**Review by pimato — APPROVED** [review]

**Review by hexyls — APPROVED** [review]

**Pull request merged**
