### PR TITLE
Prevent bonding error when block time is behind local time

### PR DESCRIPTION
**Pull request by hexyls**
closes https://github.com/protofire/omen-exchange/issues/2092

testing:
- [ ] countdown works correctly
- [ ] transition to finalize tab is simultaneous across the market top, market body, and market navigation
- [ ] can bond on market immediately after switch to finalize tab

### CODE REVIEW

**Comment by pimato** [comment]
testing:
- [ ] countdown works correctly
- [ ] transition to finalize tab is simultaneous across the market top, market body, and market navigation
- [ ] can bond on market immediately after switch to finalize tab

**Comment by Mi-Lan** [comment]
testing:
- [ ] countdown works correctly
- [ ] transition to finalize tab is simultaneous across the market top, market body, and market navigation
- [ ] can bond on market immediately after switch to finalize tab

**Review by pimato — APPROVED** [review]
Works!

**Review by Mi-Lan — APPROVED** [review]

**Review by KadenZipfel — APPROVED** [review]
LGTM!

**Pull request merged**
