### PR TITLE
Remove myMarkets filter if the user is not connected

### LINKED ISSUE #878: Markets tab is displayed if the user is not connected
With the account not connected, I would expect to either: Not see My Markets tab, or at least see it empty.

Screenshot_20200702_122613

### PR DESCRIPTION
**Pull request by mariano-aguero**
Closes #878 

If the user is not connected, the filter `myMarkets` should not be displayed

### CODE REVIEW

**Comment by pimato** [comment]
@mariano-aguero I checked what happens if the user is connected and disconnects. It switches the filter to "Open" but the market list is still thinking it is the "my markets" filter page. It would be good if the market list gets updated to the open markets.

Screenshot 2020-07-03 at 15 59 05

**Comment by mariano-aguero** [comment]
> @mariano-aguero I checked what happens if the user is connected and disconnects. It switches the filter to "Open" but the market list is still thinking it is the "my markets" filter page. It would be good if the market list gets updated to the open markets.
> 
> Screenshot 2020-07-03 at 15 59 05

Great, let me work on it

**Comment by mariano-aguero** [comment]
@pimato I update the state, when the connection change from connected to disconnected. I think this should be enough, since updating the filter status should fetch the markets again.

**Comment by pimato** [comment]
works!

**Pull request merged**
