### PR TITLE
Add weth and wbtc to currency selection on xDai

### LINKED ISSUE #1953: Enable WBTC/WETH to be used as collateral
once https://github.com/protofire/omen-exchange/pull/1921 is merged, we should enable WBTC/WETH to be used as collateral. Currently only DAI is enabled:
Bildschirmfoto 2021-06-02 um 14 45 05

for xDai tight integration, Mainnet, xDai connection.

### PR DESCRIPTION
**Pull request by Mi-Lan**
closes #1953 
- also I fixed so that correct icons are showing upon selection
- http://localhost:3000/#/0xccef28ccbd16320aa614bbf594936d9dfc8d8a09

### CODE REVIEW

**Comment by Mi-Lan** [comment]
@hexyls I was looking today couldn't figure out the issue seems that its buying okay and creating markets but when I wan't to sell i get this error could it be that it's related to relayer? I couldn't test it on just xDai since i got all my weth locked up here....
`{"error":"Relay: Transaction will fail: processing response error (body=\"{\\\"jsonrpc\\\":\\\"2.0\\\",\\\"error\\\":{\\\"code\\\":-32015,\\\"message\\\":\\\"VM execution error.\\\",\\\"data\\\":\\\"revert: CPKFactory: execTransaction Failed\\\"},\\\"id\\\":44}\", error={\"code\":-32015,\"data\":\"revert: CPKFactory: execTransaction Failed\"}, requestBody=\"{\\\"method\\\":\\\"eth_call\\\",\\\"params\\\":[{\\\"gas\\\":\\\"0x2dc6c0\\\",\\\"gasPrice\\\":\\\"0x3b9aca00\\\",\\\"from\\\":\\\"0x1b50bc65403333f921fe627eda28c119a93aa15f\\\",\\\"to\\\":\\\"0x7b9756f8a7f4208fe42fe8de8a8cc5aa9a03f356\\\",\\\"data\\\":\\\"0x68bb7c69000000000000000000000000e15ff8d6d0c880c9bc6bfd5a6baadb6491d766d0000000000000000000000000035000fc773f4a0e39fcded08a46abbdbf196fd300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000160000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002648d80ff0a0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000022000ceafdd6bc0bef976fdcd1112955828e00543c0ce00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044a22cb465000000000000000000000000ccef28ccbd16320aa614bbf594936d9dfc8d8a09000000000000000000000000000000000000000000000000000000000000000100ccef28ccbd16320aa614bbf594936d9dfc8d8a0900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000064d3c9727c00000000000000000000000000000000000000000000000000124094aa03794f0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001a5a34be9b0529006a023ccd1ff6f2045c3309768ead9e68f978f6e1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000242e1a7d4d00000000000000000000000000000000000000000000000000124094aa03794f001b50bc65403333f921fe627eda28c119a93aa15f000000000000000000000000000000000000000000000000000aa87bee538000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004106df88c44b8d539723c0bcaca54b61352b2ce8e9c1260822fdb7fa4cb8cf8c0c7895c4db5beb93412a8d59185bc32d1d6702d19d3f66fc96e38c5c53148596c51f00000000000000000000000000000000000000000000000000000000000000\\\"},\\\"latest\\\"],\\\"id\\\":44,\\\"jsonrpc\\\":\\\"2.0\\\"}\", requestMethod=\"POST\", url=\"https://rpc.xdaichain.com/\", code=SERVER_ERROR, version=web/5.0.13)"}`

**Comment by Mi-Lan** [comment]
How to test:
1) Use this market for weth http://localhost:3000/#/0xccef28ccbd16320aa614bbf594936d9dfc8d8a09
2) Buy weth from swapr 💪 
3)Send that weth to cpk address so that you can use it on xDai tight
4)buy/sell/deposit withdraw etc....

**Comment by pimato** [comment]
Connection: xDai direct

Step to reproduce:
1) Go to http://localhost:3000/#/liquidity
2) Click Connect Button
3) Pick Metamask
4) Click on the Address Button
5) Click on Button `Change`
BUG: 
Bildschirmfoto 2021-06-11 um 17 26 13

https://user-images.githubusercontent.com/5337809/121710879-4f79dd80-cada-11eb-88b1-43483e34691b.mov

**Review by pimato — APPROVED** [review]
Works good!

**Review by KadenZipfel — APPROVED** [review]
Looks good!

**Comment by Mi-Lan** [comment]
@KadenZipfel Hey men do you think this issue is maybe related to this pr? https://github.com/protofire/omen-exchange/issues/1977 I looked into it and seems that subgraph is not returning additionalSharesCost from subgraph for new xDai currencies? Could it be subgraph issue maybe? Or maybe me not handling these transactions good or missing some part?
Screenshot 2021-06-11 at 18 31 21

**Comment by KadenZipfel** [comment]
> @KadenZipfel Hey men do you think this issue #1977 is maybe related to this pr? I looked into it and seems that subgraph is not returning additionalSharesCost from subgraph for new xDai currencies? Could it be subgraph issue maybe? Or maybe me not handling these transactions good or missing some part?
> Screenshot 2021-06-11 at 18 31 21

Actually I don't think that's the issue... Left a comment here: https://github.com/protofire/omen-exchange/issues/1977#issuecomment-859722403

**Pull request merged**
