### PR TITLE
Fix disabled buy/sell buttons

### PR DESCRIPTION
**Pull request by KadenZipfel**
Closes: https://github.com/protofire/omen-exchange/issues/1722

### CODE REVIEW

**Review by hexyls — APPROVED** [review]

**Review by Mi-Lan — CHANGES_REQUESTED** [review]
Should we maybe adjust rest of UI? This doesn't look good...
Screenshot 2021-03-11 at 12 38 48
Screenshot 2021-03-11 at 12 37 51

**Comment by KadenZipfel** [comment]
> Should we maybe adjust rest of UI? This doesn't look good with zeros everywhere
> Screenshot 2021-03-11 at 12 38 48
> Screenshot 2021-03-11 at 12 37 51

Yeah good call, tough though because we don't wanna show a ton of decimals. Maybe we could display '<0.01'? @pimato any thoughts?

**Comment by pimato** [comment]
> > Should we maybe adjust rest of UI? This doesn't look good with zeros everywhere
> > Screenshot 2021-03-11 at 12 38 48
> > Screenshot 2021-03-11 at 12 37 51
> 
> Yeah good call, tough though because we don't wanna show a ton of decimals. Maybe we could display '<0.01'? @pimato any thoughts?

yeah I think that would be the easiest solution right now. I think we will fix this issue once we have the new token curation contract where we store the decimals on-chain.

**Review by pimato — APPROVED** [review]
Fixes the underlying issue.

**Comment by KadenZipfel** [comment]
I realized this '<0.01' issue is pretty time consuming as it has to be done in several files, so I exported to this issue: https://github.com/protofire/omen-exchange/issues/1738

**Review by Mi-Lan — APPROVED** [review]

**Pull request merged**
