### PR TITLE
fix/1937

### PR DESCRIPTION
**Pull request by hexyls**
closes https://github.com/protofire/omen-exchange/issues/1937

The [Omen Relay](https://github.com/hexyls/omen-relay) now includes dynamic gas pricing using the [xDai gas price oracle](https://www.xdaichain.com/for-developers/developer-resources/gas-price-oracle). It is set up to use the average gas price atm but we can easily switch to using the fastest option if need be.

To prevent issues in extreme circumstances where either the xDai network is in super high demand, the gas price oracle malfunctions, or the relay operator is malicious, I have set a `MAX_RELAY_FEE` of 0.1 xDai, anything above that will cause the relay tx to fail. Also imo if our users are paying above 0.1 xDai per tx then we should probably start looking for alternatives to xDai 🤷‍♂️ open to opinions on that though.

How to test: buy/create/fund txs should work using the xdai tight integration

### CODE REVIEW

**Comment by gem1no** [comment]
looks good, will thoroughly test tomorrow

**Review by pimato — APPROVED** [review]
Works great!

**Review by Mi-Lan — APPROVED** [review]
Works!

**Review by KadenZipfel — APPROVED** [review]
LGTM!

**Pull request merged**
