### PR TITLE
Include pool data in scalar markets view

### PR DESCRIPTION
**Pull request by KadenZipfel**
Closes: https://github.com/protofire/omen-exchange/issues/1512

### CODE REVIEW

**Review by Mi-Lan — COMMENTED** [review]
Screenshot 2021-02-02 at 21 56 52
Hmmm is the calculation correct after depositing 13 dai it shows only 5 dai as deposited...i know additional shares are bought in the background but is it that much?

**Review by pimato — APPROVED** [review]

**Review by hexyls — APPROVED** [review]
Same issue as @Mi-Lan but it looks like total user liquidity is being calculated the same way as it is in categorical markets.

Other than that looks great!

**Review by Mi-Lan — COMMENTED** [review]
Maybe i'm overthinking it but follow me here, i emptied all deposited and bought scalar markets pt and shares then:
- I deposited 15 dai
Screenshot 2021-02-04 at 17 48 57
- Deposited amount 8.18DAI
Screenshot 2021-02-04 at 18 00 01
- Short shares 1.54DAI
Screenshot 2021-02-04 at 17 59 33
- Long shares 4.18DAI
Screenshot 2021-02-04 at 17 59 45

Which adds up to 13.9 DAI? Hmm where did that 1.1 DAI go? Am i missing something?

**Review by Mi-Lan — APPROVED** [review]
Looks good in consultation with Kaden it seems that between buying of shares market odds change which causes different prices...

**Review by pRoy24 — APPROVED** [review]
lgtm

**Pull request merged**
