### PR TITLE
Deposit pool tokens to staking contract on market creation

### PR DESCRIPTION
**Pull request by KadenZipfel**
Closes: https://github.com/protofire/omen-exchange/issues/1939

Note: Please share your transaction hash when testing so I can verify that all looks good

### CODE REVIEW

**Comment by pimato** [comment]
@KadenZipfel looks like I am getting an error while trying to create a market. Error on console:
Bildschirmfoto 2021-05-31 um 23 25 48

market info:
Bildschirmfoto 2021-05-31 um 23 26 29

**Review by hexyls — APPROVED** [review]
Works! Here is my [tx](https://rinkeby.etherscan.io/tx/0x30ef582f600497ce4d692badaabfb1815eb872a5466c1ddb29d6f0dc5cd8a632)

idk if anyone else is going to experience this while testing, but for me both the in-built cpk gas estimator and the metamask gas estimator were both unable to estimate gas properly for this tx (I had to hardcode gas to get it to work). I'm not sure if it is due to complexity of the transaction or what but I will be interested to see if this is a problem for anyone else.

Also just one tip for testing - make sure you are creating markets that resolve at least 1 day from creation.

**Comment by Mi-Lan** [comment]
Screenshot 2021-06-03 at 12 10 05
Im getting this error when trying to create market?

**Comment by Mi-Lan** [comment]
But was able to create it on xDai here is transaction https://blockscout.com/xdai/mainnet/tx/0x6628a9ae384b2a920463b1ed817369c104c857ee92d6f573231caa2cf3d05029/token-transfers

**Comment by KadenZipfel** [comment]
@pimato @Mi-Lan Can you guys try again after disabling cpk failsafe as described here: https://github.com/protofire/omen-exchange/pull/1907#issuecomment-843777240 then share your tx? (Rinkeby)

I think the cpk is falsely assuming that the transaction will fail and thus not even allowing you to proceed

**Comment by hexyls** [comment]
I couldn't quite figure it out today but there could be something odd going on with timestamps causing this error. 

The error we are getting atm seems to be if the current params are executed immediately, but if you submit the same params in a later block it seems like there was never an issue to begin with.

If you make sure that `startingTimestamp` is less than the current block time then you will avoid any errors. I think this allows [`stake`](https://github.com/KadenZipfel/erc20-staking-rewards-distribution-contracts/blob/master/contracts/ERC20StakingRewardsDistribution.sol#L196) to work which uses the [`onlyRunning`](https://github.com/KadenZipfel/erc20-staking-rewards-distribution-contracts/blob/master/contracts/ERC20StakingRewardsDistribution.sol#L471) modifier which requires [`block.timestamp >= startingTimestamp`](https://github.com/KadenZipfel/erc20-staking-rewards-distribution-contracts/blob/master/contracts/ERC20StakingRewardsDistribution.sol#L471)

This is super confusing though because `startingTimestamp` must be [more than](https://github.com/KadenZipfel/erc20-staking-rewards-distribution-contracts/blob/master/contracts/ERC20StakingRewardsDistribution.sol#L106) the timestamp of the block it is included in to be valid) 🤷‍♂️ so really it should revert...

**Pull request closed without merging**
