### PR TITLE
Refactoring Base

### PR DESCRIPTION
**Pull request by Mi-Lan**
- Just so we can keep track of all changes from master if needed
- Also one suggestion so we don't end up in merge conflict of hell at the end of refactoring...I suggest that we solve conflicts as they emerge....
- And so we see those big red numbers grow 🥳

### CODE REVIEW

**Comment by pimato** [comment]
- [ ] Categorical markets
    - [ ] Create market
    - [ ] Buy
    - [ ] Sell
    - [ ] Deposit
    - [ ] Withdraw
    - [ ] Bond outcome
    - [ ] Redeem winnings
- [ ] Scalar markets
    - [ ] Create market
    - [ ] Buy
    - [ ] Sell
    - [ ] Deposit
    - [ ] Withdraw
    - [ ] Bond outcome
    - [ ] Redeem winnings
    - [ ] Position table works as expected
        - Correct payout/profit/loss
    - [ ] Market buy slider works as expected
        - Correct payout/profit/loss
- [ ] Account
    - [ ] Correct wallet balances
    - [ ] Correct omen account balances
- [ ] xDai relay
    - [ ] Deposit
    - [ ] Withdraw
- [ ] Mobile
    - Should just be relatively functional as per usual

**Comment by Mi-Lan** [comment]
- [ ] Categorical markets
    - [ ] Create market
    - [ ] Buy
    - [ ] Sell
    - [ ] Deposit
    - [ ] Withdraw
    - [ ] Bond outcome
    - [ ] Redeem winnings
- [ ] Scalar markets
    - [ ] Create market
    - [ ] Buy
    - [ ] Sell
    - [ ] Deposit
    - [ ] Withdraw
    - [ ] Bond outcome
    - [ ] Redeem winnings
    - [ ] Position table works as expected
        - Correct payout/profit/loss
    - [ ] Market buy slider works as expected
        - Correct payout/profit/loss
- [ ] Account
    - [ ] Correct wallet balances
    - [ ] Correct omen account balances
- [ ] xDai relay
    - [ ] Deposit
    - [ ] Withdraw
- [ ] Mobile
    - Should just be relatively functional as per usual

**Comment by Mi-Lan** [comment]
Screenshot 2021-08-04 at 16 00 07
Found one issue when buying shares on categorical market

**Review by Frankaus — COMMENTED** [review]
- [ ] Categorical markets
- [x]  Create market
https://rinkeby.etherscan.io/tx/0xc23532af753310601ccdbcbf68b82e2470b230b40d060134d6f383b9d21bb9e6
- [x]  Buy
https://rinkeby.etherscan.io/tx/0xb59b0493afe3515568d2c5f7b53ba2ce6b2de27d2bdcd285c5efb3e45fc32469
- [x]  Sell
https://rinkeby.etherscan.io/tx/0x0c594ed5255325c33fe11944bb7e0c82dc9a165f27ec4f153706bd37b7c19231
- [x]  Deposit
https://rinkeby.etherscan.io/tx/0x73cc4e693e2eeb33129e24b63114c1f5efba5511f848ba05546012d2c53d67cd
- [x]  Withdraw
https://rinkeby.etherscan.io/tx/0xf36d17add5e89f96009c55af5f6922ce8512a62e86b9569d2de16ce22c58df0e
- [x]  Bond outcome
https://rinkeby.etherscan.io/tx/0xe1713ee95ac37a5fd03acd02bc877b353bc8be67e3c4e49ca2e3ece5ee697e2f
- [x]  Redeem winnings
https://rinkeby.etherscan.io/tx/0x09399e5fe58cc0a2ab29cffd74769e549fabd8ecb880cd7a37b4f0d787e6552f

 - []  Scalar markets
- [x]  Create market
https://rinkeby.etherscan.io/tx/0x900aae46b70ad777991097318b79b5c71c47e69789e23fc2c3491d6ff7234b49
https://rinkeby.etherscan.io/tx/0xa9c3e869018e48842fcb8e61b7ec45e09c542e2952ed69ab00cf34f579f5d6e3
- [x]  Buy
https://rinkeby.etherscan.io/tx/0x6dcb592ddd4a7276c2994758df02392bacde08ed9f322110e15b314e7559def2
with one case of unhandled rejection error
- [x]  Sell
https://rinkeby.etherscan.io/tx/0x8268a481f135c3939927a58936f584b551655475fe100f033a71eed46b1abba7
- [x]  Deposit
https://rinkeby.etherscan.io/tx/0x8e0ffa78dd631cdbbf15fd8c92efcc4ff53b8583fed3b0a077f19ec5d25e9405
- [ ]  Withdraw

- [x]  Bond outcome
https://rinkeby.etherscan.io/tx/0x0832b29d5805f2061a65064dde7e8c7b443c0dcbd8f34b736469e1e5e6f718b8
- [x]  Redeem winnings
https://rinkeby.etherscan.io/tx/0xd8ac2b6099e77b914483932251fff41ef3269c2c462885c1bb03c82312e4b756
- [x]  Position table works as expected
    Correct payout/profit/loss
- [ ]  Market buy slider works as expected
    Correct payout/profit/loss

Account
- [x]  Correct wallet balances
- [ ]  Correct omen account balances
- [ ]  xDai relay
- [ ]  Deposit
- [ ]  Withdraw
- [ ]  Mobile
- [ ] Should just be relatively functional as per usual

**Comment by hexyls** [comment]
- [ ] Categorical markets
    - [x] Create market
    - [x] Buy
    - [x] Sell
    - [x] Deposit
    - [ ] Withdraw: Error when you are the only LP and withdraw all liquidity: Resolved by #2154
    - [x] Bond outcome
    - [x] Redeem winnings
- [ ] Scalar markets
    - [x] Create market
    - [x] Buy
    - [x] Sell
    - [x] Deposit
    - [ ] Withdraw: Same issue as above
    - [x] Bond outcome
    - [x] Redeem winnings
    - [ ] Position table works as expected
        - Correct payout/profit/loss
    - [ ] Market buy slider works as expected
        - Correct payout/profit/loss
- [x] Account
    - [x] Correct wallet balances
    - [x] Correct omen account balances
- [ ] xDai relay
    - [x] Deposit
    - [ ] Withdraw: Error when withdrawing max xDAI: Resolved by https://github.com/protofire/omen-exchange/pull/2155
- [ ] Mobile
    - Should just be relatively functional as per usual

**Comment by Frankaus** [comment]
- [x] Categorical markets
- [x]  Create market
https://rinkeby.etherscan.io/tx/0x96f92c9f575746d625f232fba4d71c1d80bde03f52e90ed4b5567ced22a406d7
- [x]  Buy
https://rinkeby.etherscan.io/tx/0xb9f5aef2306a38d4d9e05b09078f85788b3a89c25620db3c82ee35462418e109
bought 2DAI against 1DAI in LP and worked out fine
- [x]  Sell
https://rinkeby.etherscan.io/tx/0x45f949217ce4de876fceac41e5a0f05db10c0ef824aa9d2a66c6c89d97c0b2eb
<0.01 rounding shows properly
- [x]  Deposit
https://rinkeby.etherscan.io/tx/0xb8dabf2a0e136d6ba546dff774a4aa08f6815ce157b9bf6b83b42d89d12436db
- [x]  Withdraw
https://rinkeby.etherscan.io/tx/0x69575e18431454f0c030c8f41a9e03595302fbf8837a3fa6c185dc2461ca81c8
- [x]  Bond outcome
https://rinkeby.etherscan.io/tx/0x3155171f025c2fb8f48a566c51b3dc8aac0cc24cd1fa816ce53fcacc75910edd
- [x]  Redeem winnings
https://rinkeby.etherscan.io/tx/0x59b015389d0cbacbbca08273bbdf90b1550afeaabac3aa04371bba5c7bea1e35

 - [x]  Scalar markets
- [x]  Create market
https://rinkeby.etherscan.io/tx/0xfcb1aefbb67645309e0298d6adb792f52cecf7db7a30b6eb32ac5f664fa58737
- [x]  Buy
https://rinkeby.etherscan.io/tx/0x38641a514eb547df459913c4d3261cfda5da41216220b139d73e99844d9f9ef9
- [x]  Sell
https://rinkeby.etherscan.io/tx/0xc55f3043c232f311c22ce27eb0b203bf21ec15627d0bce6a31130e37f08302b1
- [x]  Deposit
https://rinkeby.etherscan.io/tx/0x1788878cb74042412d1ed11a304271cd4633f314f43c39dfde758e2e733c35c7
- [x]  Withdraw
https://rinkeby.etherscan.io/tx/0x75ed5afccdb65c95655792e7b2d8dfb297aa1408c0dc35f91efb497e6d646238
- [x]  Bond outcome
https://rinkeby.etherscan.io/tx/0x9ea74ad8ca9b278c02a3e291b2750b4ea779004f32e045007a1b0e87c34fc3ea
- [x]  Redeem winnings
https://rinkeby.etherscan.io/tx/0x5a472e221b936fdc8087247b0999e135a48f26e5a6980c82a6822fa0deb2b4f1
- [x]  Position table works as expected
- [x]  Market buy slider works as expected

Account
- [x]  Correct wallet balances
- [x]  Correct omen account balances
- [x]  xDai relay
switch correctly
- [x]  Deposit
https://etherscan.io/tx/0x3cbfd5517fb13b3b59ca10e47060574617e2bfb4124c2295beaa78fa2977bfad
- [ ]  Withdraw
- [x]  Mobile

**Review by pimato — APPROVED** [review]
Works!

**Comment by KadenZipfel** [comment]
Testing: 
- [ ] Categorical markets
    - [ ] Create market
    - [ ] Buy
    - [ ] Sell
    - [ ] Deposit
    - [ ] Withdraw
    - [ ] Bond outcome
    - [ ] Redeem winnings
- [ ] Scalar markets
    - [ ] Create market
    - [ ] Buy
    - [ ] Sell
    - [ ] Deposit
    - [ ] Withdraw
    - [ ] Bond outcome
    - [ ] Redeem winnings
    - [ ] Position table works as expected
        - Correct payout/profit/loss
    - [ ] Market buy slider works as expected
        - Correct payout/profit/loss
- [ ] Account
    - [ ] Correct wallet balances
    - [ ] Correct omen account balances
- [ ] xDai relay
    - [ ] Deposit
    - [ ] Withdraw
- [ ] Mobile
    - Should just be relatively functional as per usual

**Review by KadenZipfel — APPROVED** [review]
LGTM!

**Pull request merged**
