### PR TITLE
[WIP] Add market overview widget

### PR DESCRIPTION
**Pull request by KadenZipfel**
Will close https://github.com/protofire/omen-exchange/issues/817

**Todo:**
- [x] Display 24h trade volume instead of total volume
  - Partly dependent on https://github.com/protofire/omen-exchange/issues/1092
- [x] Optimize for mobile
- [x] Properly calculate finalizing progress
  - May require modification to the subgraph

### CODE REVIEW

**Comment by pimato** [comment]
Hey @KadenZipfel, seems like there are issues because of the `MKR` symbol again?
Screenshot 2020-09-05 at 15 22 04

**Comment by KadenZipfel** [comment]
> Hey @KadenZipfel, seems like there are issues because of the `MKR` symbol again?

Yep, it will be there until we merge the https://github.com/protofire/omen-exchange/pull/1096 and rebase on top of it

**Comment by pimato** [comment]
As requested, here is the first version of the market overview for mobile:
https://github.com/protofire/omen-exchange/issues/1108

**Comment by pimato** [comment]
I found a bug which get triggered when the user clicks on the trade history dropdown:
Screenshot 2020-09-11 at 10 17 14

**Comment by pimato** [comment]
will move that bug into its own issue and gonna merge the big PR now!

**Review by pimato — APPROVED** [review]

**Pull request merged**
