### PR TITLE
Pool liquidity component consolidation 

### PR DESCRIPTION
**Pull request by Mi-Lan**
Consolidated scalar market pool and categorical market pool and put the market_pool_container inside pages folder.
How to test:

- [ ] Make sure depositing and withdrawing works 
- [ ] Categorical
- [ ] Scalar markets

### CODE REVIEW

**Comment by pimato** [comment]
Deposit:
- [ ] Categorical
- [ ] Scalar markets

Withdraw:
- [ ] Categorical
- [ ] Scalar markets

**Review by pimato — APPROVED** [review]
LGTM!

**Review by KadenZipfel — APPROVED** [review]
Looks good! Super nice to have the components cleaned up like this. Deposit and withdraw worked well. Hope you don't mind I cleanup the container a little bit (mostly just adding new lines between things) to make it a little more readable for myself

**Review by hexyls — APPROVED** [review]
Great work! 

- [x] Make sure depositing and withdrawing works 
- [x] Categorical
- [x] Scalar markets

**Comment by Mi-Lan** [comment]
> Looks good! Super nice to have the components cleaned up like this. Deposit and withdraw worked well. Hope you don't mind I cleanup the container a little bit (mostly just adding new lines between things) to make it a little more readable for myself

Of course not! Thank you! Yeah I kinda didn't clean it up good and made it readable cause I didn't know how. But looks way better now. GJ

**Pull request merged**
