### PR TITLE
Disable withdraw tab when user has no liquidity

### PR DESCRIPTION
**Pull request by hexyls**
closes https://github.com/protofire/omen-exchange/issues/2065

Testing for both categorical and scalar:

- [ ] If the user has no liquidity when the Deposit tab is selected the Withdraw tab is disabled 
- [ ] If the user has liquidity, the Withdraw tab is selected, and the user withdraws all liquidity, the Withdraw tab is still enabled but switching back to the Deposit tab disables it

### CODE REVIEW

**Comment by KadenZipfel** [comment]
Testing:
- [ ] If the user has no liquidity when the Deposit tab is selected the Withdraw tab is disabled 
- [ ] If the user has liquidity, the Withdraw tab is selected, and the user withdraws all liquidity, the Withdraw tab is still enabled but switching back to the Deposit tab disables it

**Review by KadenZipfel — APPROVED** [review]
🔥

**Comment by pimato** [comment]
- [ ] If the user has no liquidity when the Deposit tab is selected the Withdraw tab is disabled 
- [ ] If the user has liquidity, the Withdraw tab is selected, and the user withdraws all liquidity, the Withdraw tab is still enabled but switching back to the Deposit tab disables it

**Review by pimato — APPROVED** [review]
Great work!

**Pull request merged**
