### PR TITLE
Scalar market closed

### PR DESCRIPTION
**Pull request by KadenZipfel**
Closes https://github.com/protofire/omen-exchange/issues/1442

### CODE REVIEW

**Comment by pimato** [comment]
Hey @KadenZipfel , 

nothing happens after me clicking the `Create Market - Button`:
Bildschirmfoto 2020-12-15 um 20 57 31

logs:
Bildschirmfoto 2020-12-15 um 20 58 41

**Review by pimato — CHANGES_REQUESTED** [review]
see comment.

**Comment by KadenZipfel** [comment]
> Hey @KadenZipfel ,
> 
> nothing happens after me clicking the `Create Market - Button`:

Weird, it works for me... Do you have an env file with the proper subgraph? The scalar markets branch still uses the env file until we merge. Also might help to restart your server

**Comment by hexyls** [comment]
Hey does anyone have a link to a market I can test this with? Otherwise will hold off on a review until subgraphs are back online 👍

**Comment by KadenZipfel** [comment]
> Hey does anyone have a link to a market I can test this with? Otherwise will hold off on a review until subgraphs are back online 👍

This should give you all the closed scalar markets: http://localhost:3000/#/newest/curation-source/None?state=CLOSED&tag=[

But ideally we should test through the whole cycle, seeing what happens with markets that you do and don't have outcome shares in, as well as the process of finalizing, resolving, and redeeming. That being said, we could do most of those full lifecycle tests after merging if we have a pretty good idea that this PR is good.

**Review by hexyls — APPROVED** [review]

**Review by Mi-Lan — CHANGES_REQUESTED** [review]
@KadenZipfel So when i tried to redeem winning outcome on one scalar market. I got error...dunno if this is related to this pr....
Screenshot 2020-12-21 at 12 28 22

**Comment by KadenZipfel** [comment]
> @KadenZipfel So when i tried to redeem winning outcome on one scalar market. I got error...dunno if this is related to this pr....

I can't reproduce this :/ can you please console.log your `conditionId` in `cpk.redeemPositions` and share?

**Comment by Mi-Lan** [comment]
> > @KadenZipfel So when i tried to redeem winning outcome on one scalar market. I got error...dunno if this is related to this pr....
> 
> I can't reproduce this :/ can you please console.log your `conditionId` in `cpk.redeemPositions` and share?

@KadenZipfel hmmm while on branch fix/1474 i tried to reedem it and it worked metamask transaction was prompted...i didn't reedem it i'm saving it so we can test it here...

**Comment by Mi-Lan** [comment]
> > @KadenZipfel So when i tried to redeem winning outcome on one scalar market. I got error...dunno if this is related to this pr....
> 
> I can't reproduce this :/ can you please console.log your `conditionId` in `cpk.redeemPositions` and share?

not sure what property specifically you meant "0x53fb7fadac1f364db1c72f72c0e50ac0ac0704f5e3be7c0bba057ae072c230f5" maybe this? here is the screenshot

**Comment by pimato** [comment]
Hey @KadenZipfel the timeout is still 24h:
Bildschirmfoto 2020-12-23 um 15 31 21

we should reduce it on Rinkeby to 3 minutes!

**Comment by pimato** [comment]
But overall testing seems all to work!

**Review by pimato — CHANGES_REQUESTED** [review]
please change the reality.eth timeout to 3 minutes on Rinkeby

**Review by pimato — APPROVED** [review]
looks good!

**Pull request merged**
